import type { Localized } from "@/lib/i18n";
const en = {
  requestSearch: "Search requests", requestSearchPlaceholder: "Name, email, reference, business or assignee",
  unsavedTitle: "Unsaved form changes", discardBody: "Your changes have not been saved. Discard them and close this form?", discard: "Discard changes",
  localNote: "Orders and enquiries in this preview are stored in this browser. Payments and notifications are simulated.",
  add: "New enquiry", export: "Export CSV", orderCount: "Orders", orderValue: "Product subtotal", openCount: "Awaiting follow-up", customers: "Customers", customerCount: "Customers", latest: "Latest activity", view: "View details", close: "Close details", remove: "Move to Trash", confirmRemove: "Move this record and its notification previews to Trash? You can restore them for 30 days.", cancel: "Cancel", create: "Create enquiry", quantity: "Quantity", product: "Product", copied: "Copied", copy: "Copy preview", noCustomer: "No customers yet", noCustomerBody: "Customers appear when an order, message, or newsletter signup is received.", noData: "No records yet", sample: "Add sample records", filtered: "No matching records", subscriber: "Newsletter", newFirst: "Newest first", oldFirst: "Oldest first", records: "Records", allStatuses: "All statuses", select: "Select a record to follow up", confirm: "Move to Trash", print: "Print summary", totalNote: "Product subtotal only. Shipping and final payment are confirmed separately.", save: "Save changes", failed: "Could not save. Your input is kept; please try again.", preview: "Preview", previous: "Previous", next: "Next", page: "Page", of: "of", unavailable: "Store operations are available in local preview mode.", created: "Enquiry created", deleted: "Moved to Trash", emailNotes: "Notification previews are generated when a record is created. No email is sent.", history: "Customer history",
};
export const operationsCopy: Localized<typeof en> = {
  en,
  ar: {
  "requestSearch": "البحث في الاستفسارات",
  "requestSearchPlaceholder": "الاسم أو البريد الإلكتروني أو المرجع أو النشاط التجاري أو المسؤول",
  "unsavedTitle": "تغييرات غير محفوظة في النموذج",
  "discardBody": "لم تُحفظ تغييراتك. هل تريد تجاهلها وإغلاق النموذج؟",
  "discard": "تجاهل التغييرات",
  "localNote": "تُحفظ طلبات هذه المعاينة واستفساراتها في هذا المتصفح. المدفوعات والإشعارات محاكاة.",
  "add": "استفسار جديد",
  "export": "تصدير CSV",
  "orderCount": "الطلبات",
  "orderValue": "المجموع الفرعي للمنتجات",
  "openCount": "بانتظار المتابعة",
  "customers": "العملاء",
  "customerCount": "العملاء",
  "latest": "آخر نشاط",
  "view": "عرض التفاصيل",
  "close": "إغلاق التفاصيل",
  "remove": "نقل إلى سلة المحذوفات",
  "confirmRemove": "هل تريد نقل هذا السجل ومعاينات إشعاراته إلى سلة المحذوفات؟ يمكنك استعادتها خلال 30 يومًا.",
  "cancel": "إلغاء",
  "create": "إنشاء استفسار",
  "quantity": "الكمية",
  "product": "المنتج",
  "copied": "تم النسخ",
  "copy": "نسخ المعاينة",
  "noCustomer": "لا يوجد عملاء بعد",
  "noCustomerBody": "يظهر العملاء عند تلقي طلب أو رسالة أو اشتراك في النشرة البريدية.",
  "noData": "لا توجد سجلات بعد",
  "sample": "إضافة سجلات نموذجية",
  "filtered": "لا توجد سجلات مطابقة",
  "subscriber": "النشرة البريدية",
  "newFirst": "الأحدث أولًا",
  "oldFirst": "الأقدم أولًا",
  "records": "السجلات",
  "allStatuses": "جميع الحالات",
  "select": "اختر سجلًا للمتابعة",
  "confirm": "نقل إلى سلة المحذوفات",
  "print": "طباعة الملخص",
  "totalNote": "المجموع الفرعي للمنتجات فقط. تُؤكد تكلفة الشحن والدفع النهائي بصورة منفصلة.",
  "save": "حفظ التغييرات",
  "failed": "تعذّر الحفظ. ما زالت بياناتك محفوظة؛ يُرجى المحاولة مجددًا.",
  "preview": "معاينة",
  "previous": "السابق",
  "next": "التالي",
  "page": "صفحة",
  "of": "من",
  "unavailable": "تتوفر إدارة أعمال المتجر في وضع المعاينة المحلية.",
  "created": "تم إنشاء الاستفسار",
  "deleted": "تم النقل إلى سلة المحذوفات",
  "emailNotes": "تُنشأ معاينات الإشعارات عند إنشاء السجل. لا تُرسل رسائل بريد إلكتروني.",
  "history": "سجل العميل"
},
  th: {
    requestSearch: "ค้นหาคำขอลูกค้า", requestSearchPlaceholder: "ชื่อ อีเมล เลขอ้างอิง ธุรกิจ หรือผู้รับผิดชอบ",
    unsavedTitle: "มีข้อมูลที่ยังไม่ได้บันทึก", discardBody: "ข้อมูลที่แก้ไขยังไม่ได้บันทึก ต้องการละทิ้งการแก้ไขและปิดฟอร์ม?", discard: "ละทิ้งการแก้ไข",
    localNote: "รายการสั่งซื้อและคำถามตัวอย่างเก็บในเบราว์เซอร์นี้ การชำระเงินและการแจ้งเตือนเป็นการจำลอง",
    add: "เพิ่มคำสอบถาม", export: "ส่งออก CSV", orderCount: "รายการสั่งซื้อ", orderValue: "ยอดสินค้า", openCount: "รอดำเนินการ", customers: "ลูกค้า", customerCount: "ลูกค้า", latest: "กิจกรรมล่าสุด", view: "ดูรายละเอียด", close: "ปิดรายละเอียด", remove: "ย้ายไปถังขยะ", confirmRemove: "ย้ายรายการและตัวอย่างการแจ้งเตือนไปถังขยะ? คุณสามารถกู้คืนได้ภายใน 30 วัน", cancel: "ยกเลิก", create: "บันทึกคำสอบถาม", quantity: "จำนวน", product: "สินค้า", copied: "คัดลอกแล้ว", copy: "คัดลอกตัวอย่าง", noCustomer: "ยังไม่มีลูกค้า", noCustomerBody: "ลูกค้าจะแสดงเมื่อได้รับรายการสั่งซื้อ ข้อความ หรือการสมัครรับข่าวสาร", noData: "ยังไม่มีรายการ", sample: "เพิ่มข้อมูลตัวอย่าง", filtered: "ไม่พบรายการที่ตรงกับการค้นหา", subscriber: "รับข่าวสาร", newFirst: "ใหม่ก่อน", oldFirst: "เก่าก่อน", records: "รายการ", allStatuses: "ทุกสถานะ", select: "เลือกรายการเพื่อติดตาม", confirm: "ย้ายไปถังขยะ", print: "พิมพ์สรุป", totalNote: "ยอดสินค้าเท่านั้น ค่าจัดส่งและการชำระเงินจะยืนยันแยกต่างหาก", save: "บันทึกการเปลี่ยนแปลง", failed: "บันทึกไม่สำเร็จ ข้อมูลที่กรอกยังอยู่ กรุณาลองอีกครั้ง", preview: "ตัวอย่าง", previous: "ก่อนหน้า", next: "ถัดไป", page: "หน้า", of: "จาก", unavailable: "การจัดการร้านพร้อมใช้งานในโหมดตัวอย่างในเครื่อง", created: "บันทึกคำสอบถามแล้ว", deleted: "ย้ายไปถังขยะแล้ว", emailNotes: "ตัวอย่างการแจ้งเตือนจะสร้างเมื่อบันทึกรายการ ไม่มีการส่งอีเมลจริง", history: "ประวัติลูกค้า",
  },
};
