// Arabic text for contextual CMS controls.
export const cmsArabicUi: Record<string, string> = {
  "Your selected image has not been saved. Leave the media library?": "لم تُحفظ الصورة المختارة. هل تريد مغادرة مكتبة الوسائط؟",
  "Work recovered. Review it before saving.": "تمت استعادة العمل. راجعه قبل الحفظ.",
  "Record pages": "صفحات السجلات",
  "Save the draft before previewing.": "احفظ المسودة قبل المعاينة.",
  "Recover unfinished work": "استعادة العمل غير المكتمل",
  "Unfinished work from your previous session is available.": "يتوفر عمل غير مكتمل من جلستك السابقة.",
  "Recover work": "استعادة العمل",
  "Discard recovered work?": "هل تريد تجاهل العمل المستعاد؟",
  "Discard recovery": "تجاهل النسخة المستعادة",
  "Browser recovery storage is unavailable. Save your changes before leaving.": "تعذّر تخزين نسخة الاستعادة في المتصفح. احفظ تغييراتك قبل المغادرة.",
  "Start product case study": "بدء دراسة حالة لمنتج",
  "Configured services": "الخدمات المُعدّة",
  "Recovery copy saved in this browser · expires in 7 days": "حُفظت نسخة استعادة في هذا المتصفح · تنتهي صلاحيتها بعد 7 أيام",
  "IDs and URL slugs must be unique.": "يجب ألّا تتكرر المعرّفات ومسارات الروابط.",
  "Removed expired Trash entries": "تم حذف عناصر سلة المحذوفات التي انتهت مدة الاحتفاظ بها",
  "Add link": "إضافة رابط",
  "Link text": "نص الرابط",
  "Use / for a page on this website, or https://": "استخدم / لصفحة داخل هذا الموقع، أو https:// لرابط خارجي",
  "Remove link": "إزالة الرابط",
  "Lists, links, images, and tables": "القوائم والروابط والصور والجداول",
  "Bullet list (one item per line)": "قائمة نقطية (عنصر واحد في كل سطر)",
  "Section links": "روابط القسم",
  "Add supporting image": "إضافة صورة توضيحية",
  "Image caption": "تعليق الصورة",
  "Remove image": "إزالة الصورة",
  "Add comparison table": "إضافة جدول مقارنة",
  "Comparison table": "جدول المقارنة",
  "Remove table": "إزالة الجدول",
  "Column heading": "عنوان العمود",
  "Row": "صف",
  "Remove row": "إزالة الصف",
  "Add row": "إضافة صف",
  "Add column": "إضافة عمود",
  "Remove last column": "إزالة العمود الأخير",
  "Previously published URLs redirect automatically after the new URL is published.": "تُوجَّه الروابط المنشورة سابقًا تلقائيًا بعد نشر الرابط الجديد.",
  "Featured article": "مقال مميز",
  "Actual publication date (optional)": "تاريخ النشر الفعلي (اختياري)",
  "Content update date (optional)": "تاريخ تحديث المحتوى (اختياري)",
  "Previous URLs:": "الروابط السابقة:",
  "Editorial review": "المراجعة التحريرية",
  "Internal notes (never shown publicly)": "ملاحظات داخلية (لا تظهر للزوار)",
  "Requires factual review before publication": "يتطلب مراجعة الحقائق قبل النشر",
  "Publication is blocked until the evidence is reviewed and this requirement is cleared.": "لا يمكن النشر حتى تُراجع الأدلة ويُلغى تحديد هذا المتطلب.",
  "Translation review": "مراجعة الترجمة",
  "Core fields complete": "الحقول الأساسية مكتملة",
  "Incomplete": "غير مكتمل",
  "Review meaning and factual accuracy in both languages before publishing.": "راجع المعنى ودقة الحقائق باللغات الثلاث قبل النشر.",
  "Choose an existing category or enter a new one.": "اختر فئة موجودة أو أدخل فئة جديدة.",
  "Author, images, and SEO": "الكاتب والصور وتحسين الظهور في البحث",
  "Author (only when verified)": "الكاتب (بعد التحقق فقط)",
  "Uses the store name when empty.": "يُستخدم اسم المتجر إذا تُرك الحقل فارغًا.",
  "Search result title": "عنوان نتيجة البحث",
  "Uses the article title when empty.": "يُستخدم عنوان المقال إذا تُرك الحقل فارغًا.",
  "Search result description": "وصف نتيجة البحث",
  "Uses the article excerpt when empty.": "يُستخدم مقتطف المقال إذا تُرك الحقل فارغًا.",
  "Use a separate social sharing image": "استخدام صورة خاصة للمشاركة على وسائل التواصل",
  "References": "المراجع",
  "Related products": "المنتجات ذات الصلة",
  "Backup prepared. Check your downloads folder.": "تم تجهيز النسخة الاحتياطية. راجع مجلد التنزيلات.",
  "Backup failed. Check storage availability and try again.": "تعذّر النسخ الاحتياطي. تحقق من توفر التخزين وأعد المحاولة.",
  "This backup could not be verified or exceeds the supported size. Choose a complete CMS backup.": "تعذّر التحقق من هذه النسخة الاحتياطية أو تجاوز حجمها الحد المسموح. اختر نسخة كاملة من نظام الإدارة.",
  "Draft and media restored. Review before publishing.": "تمت استعادة المسودة والوسائط. راجعها قبل النشر.",
  "Restoration could not be confirmed. Reload the latest content and inspect the backup again.": "تعذّر تأكيد الاستعادة. أعد تحميل أحدث محتوى وافحص النسخة الاحتياطية مجددًا.",
  "Complete backup": "نسخة احتياطية كاملة",
  "Includes content, drafts, uploaded images, revision history, and Trash. Bundled website assets remain in the project. Keep backups in secure storage.": "تشمل المحتوى والمسودات والصور المرفوعة وسجل الإصدارات وسلة المحذوفات. تبقى ملفات الموقع المرفقة ضمن المشروع. احتفظ بالنسخ الاحتياطية في مكان آمن.",
  "Download backup": "تنزيل نسخة احتياطية",
  "Inspect backup to restore": "فحص النسخة الاحتياطية لاستعادتها",
  "Choose backup": "اختيار نسخة احتياطية",
  "Processing…": "جارٍ المعالجة…",
  "Save current edits before managing backups.": "احفظ التعديلات الحالية قبل إدارة النسخ الاحتياطية.",
  "Review backup": "مراجعة النسخة الاحتياطية",
  "Close": "إغلاق",
  "Restore into the draft. The current website changes only when you review and publish.": "تُستعاد النسخة إلى المسودة. يتغير الموقع الحالي بعد المراجعة والنشر فقط.",
  "Cancel": "إلغاء",
  "Restore as draft": "استعادة كمسودة",
  "Selling & service details": "تفاصيل البيع والخدمة",
  "Enter approved facts in both languages. Unconfirmed terms continue to invite customers to ask the team.": "أدخل المعلومات المعتمدة باللغات الثلاث. تدعو الشروط غير المؤكدة العملاء إلى التواصل مع الفريق.",
  "Confirmed": "مؤكد",
  "Needs confirmation": "بحاجة إلى تأكيد",
  "The store owner has confirmed these details": "أكد مالك المتجر هذه التفاصيل",
  "Title": "العنوان",
  "Summary": "الملخص",
  "Details": "التفاصيل",
  "Review conflicting edits": "مراجعة التعديلات المتعارضة",
  "Deleted": "محذوف",
  "Choose a version for each field. Independent edits will be kept automatically.": "اختر نسخة لكل حقل. تُحفظ التعديلات غير المتعارضة تلقائيًا.",
  "My edit": "تعديلي",
  "Latest saved": "أحدث نسخة محفوظة",
  "Keep editing": "متابعة التعديل",
  "Apply selected versions": "تطبيق النسخ المختارة",
  "Pages": "الصفحات",
  "Unable to load revision history.": "تعذّر تحميل سجل الإصدارات.",
  "Unable to inspect this revision. Reload the latest content.": "تعذّر فحص هذا الإصدار. أعد تحميل أحدث محتوى.",
  "Draft restored. Review and publish when ready.": "تمت استعادة المسودة. راجعها وانشرها عندما تصبح جاهزة.",
  "Restoration could not be confirmed. Reload the latest content before retrying.": "تعذّر تأكيد الاستعادة. أعد تحميل أحدث محتوى قبل إعادة المحاولة.",
  "Content revision history": "سجل إصدارات المحتوى",
  "Compare earlier revisions with the current draft. Restoring changes the draft; publication is a separate step.": "قارن الإصدارات السابقة بالمسودة الحالية. تغيّر الاستعادة المسودة، ثم يمكنك نشرها في خطوة مستقلة.",
  "Save current edits before restoring a revision.": "احفظ التعديلات الحالية قبل استعادة إصدار سابق.",
  "Revision": "الإصدار",
  "Compare": "مقارنة",
  "Revision history appears after changes are saved.": "يظهر سجل الإصدارات بعد حفظ التغييرات.",
  "Compare revision": "مقارنة الإصدار",
  "The current draft is on the left; the revision to restore is on the right.": "تُعرض المسودة الحالية والإصدار المطلوب استعادته جنبًا إلى جنب.",
  "Recover prepared image": "استعادة الصورة المجهزة",
  "A prepared image is available": "تتوفر صورة مجهزة",
  "Recover your image and descriptions to continue. Images upload only after you submit.": "استعد الصورة وأوصافها للمتابعة. تُرفع الصور بعد الإرسال فقط.",
  "Recover image": "استعادة الصورة",
  "Discard image recovery?": "هل تريد تجاهل نسخة استعادة الصورة؟",
  "Remove this browser copy. Use Cleanup for uploaded files confirmed unreferenced.": "احذف هذه النسخة من المتصفح. استخدم حذف الملفات غير المستخدمة للملفات المرفوعة التي تأكد عدم ارتباطها بالمحتوى.",
  "Browser image recovery is unavailable. Keep this page open until saving finishes.": "استعادة الصورة من المتصفح غير متاحة. أبقِ الصفحة مفتوحة حتى يكتمل الحفظ.",
  "Added": "مضاف",
  "Removed": "محذوف",
  "Updated": "محدّث",
  "Before": "قبل",
  "After": "بعد",
  "Unable to review this revision. Close and reload the latest content.": "تعذّرت مراجعة هذا الإصدار. أغلق النافذة وأعد تحميل أحدث محتوى.",
  "Reviewed changes published.": "تم نشر التغييرات التي راجعتها.",
  "An article still requires factual review. Return to its editorial notes and finish the review before publishing.": "لا يزال أحد المقالات بحاجة إلى مراجعة الحقائق. عُد إلى ملاحظاته التحريرية وأكمل المراجعة قبل النشر.",
  "An owner account is required to publish.": "يلزم حساب مالك المتجر للنشر.",
  "Publishing could not be confirmed. Reload the latest content before trying again.": "تعذّر تأكيد النشر. أعد تحميل أحدث محتوى قبل إعادة المحاولة.",
  "Review before publishing": "المراجعة قبل النشر",
  "Compare the saved draft with the current website. Each record’s status still determines whether it appears publicly.": "قارن المسودة المحفوظة بالموقع الحالي. تحدد حالة كل سجل ما إذا كان سيظهر للزوار.",
  "Loading…": "جارٍ التحميل…",
  "Publishing scope": "نطاق النشر",
  "All saved changes": "جميع التغييرات المحفوظة",
  "Selected articles or products": "المقالات أو المنتجات المختارة",
  "Other edits stay in draft. Media required by selected records is preserved.": "تبقى التعديلات الأخرى في المسودة. تُحفظ الوسائط اللازمة للسجلات المختارة.",
  "No changes waiting to publish.": "لا توجد تغييرات بانتظار النشر.",
  "Back to editing": "العودة إلى التعديل",
  "Publish reviewed changes": "نشر التغييرات المراجعة",
  "Could not check readiness. Sign in as an owner and retry.": "تعذّر فحص الجاهزية. سجّل الدخول بحساب مالك المتجر وأعد المحاولة.",
  "Launch preparation": "التحضير للإطلاق",
  "Check setup": "فحص الإعدادات",
  "Checks configuration and published business details. Live services, backup restoration, and buying journeys still need a staging rehearsal.": "يفحص الإعدادات وتفاصيل العمل المنشورة. يلزم أيضًا اختبار الخدمات الفعلية واستعادة النسخ الاحتياطية ومسار الشراء في بيئة التجربة.",
  "Configured": "تم الإعداد",
  "Pending": "قيد الانتظار",
  "Folder access is unavailable. Use Chrome/Edge or the backup CLI.": "الوصول إلى المجلد غير متاح. استخدم Chrome أو Edge أو أداة النسخ الاحتياطي من سطر الأوامر.",
  "Paused. Choose the same folder to continue.": "متوقف مؤقتًا. اختر المجلد نفسه للمتابعة.",
  "Transfer failed. Existing data was preserved.": "تعذّر النقل. تم الحفاظ على البيانات الحالية.",
  "Backup complete. Every file was verified; keep the entire folder in a safe place.": "اكتمل النسخ الاحتياطي وتم التحقق من كل ملف. احتفظ بالمجلد كاملًا في مكان آمن.",
  "Restore succeeded, but the latest content could not load. Reload the CMS.": "نجحت الاستعادة، لكن تعذّر تحميل أحدث محتوى. أعد تحميل نظام الإدارة.",
  "Restored as a draft. Review and publish separately.": "تمت الاستعادة كمسودة. راجعها ثم انشرها في خطوة مستقلة.",
  "Resumable folder backup": "نسخ احتياطي إلى مجلد مع إمكانية الاستئناف",
  "Save to a folder in 512 KB parts, up to 2 GB. Pause and choose the same folder to resume within 24 hours. Every file is checked against its manifest.": "احفظ إلى مجلد بأجزاء حجمها 512 كيلوبايت، وبحد إجمالي 2 غيغابايت. يمكنك الإيقاف واختيار المجلد نفسه للاستئناف خلال 24 ساعة. يُتحقق من كل ملف بمقارنته ببياناته المسجلة.",
  "Export / resume": "تصدير / استئناف",
  "Choose restore folder": "اختيار مجلد الاستعادة",
  "Manage transfers": "إدارة عمليات النقل",
  "Folder access is unavailable in this browser. Use Chrome/Edge, the small-archive controls above, or the documented backup CLI.": "الوصول إلى المجلد غير متاح في هذا المتصفح. استخدم Chrome أو Edge، أو أدوات الأرشيف الصغير أعلاه، أو أداة النسخ الاحتياطي الموضّحة في التوثيق.",
  "CLI alternative": "بديل عبر سطر الأوامر",
  "Run locally and sign in when prompted. Credentials are not placed in command arguments. Keep manifest.json and the complete chunks folder together.": "شغّل الأداة محليًا وسجّل الدخول عند الطلب. لا تُدرج بيانات الدخول ضمن معاملات الأمر. احتفظ بملف manifest.json ومجلد chunks كاملًا معًا.",
  "Selected folder": "المجلد المختار",
  "files": "ملفات",
  "revision": "الإصدار",
  "Selection does not upload. Prepare the restore to transfer and verify files, then review before confirming the draft recovery.": "اختيار الملفات لا يرفعها. جهّز الاستعادة لنقل الملفات والتحقق منها، ثم راجعها قبل تأكيد استعادة المسودة.",
  "Prepare restore / resume": "تجهيز الاستعادة / الاستئناف",
  "Backup transfer progress": "تقدم نقل النسخة الاحتياطية",
  "Verifying": "جارٍ التحقق",
  "Downloading": "جارٍ التنزيل",
  "Uploading": "جارٍ الرفع",
  "Pause transfer": "إيقاف النقل مؤقتًا",
  "Removing temporary parts": "جارٍ حذف الأجزاء المؤقتة",
  "Retry allowance reached. Review the transfer status, then choose the folder to begin another attempt.": "بلغت الحد المسموح للمحاولات. راجع حالة النقل، ثم اختر المجلد لبدء محاولة أخرى.",
  "Your transfers": "عمليات النقل الخاصة بك",
  "No transfers.": "لا توجد عمليات نقل.",
  "Export": "تصدير",
  "Restore": "استعادة",
  "Expires": "تنتهي الصلاحية",
  "Remove transfer": "حذف عملية النقل",
  "Remove this transfer?": "هل تريد حذف عملية النقل هذه؟",
  "This removes temporary transfer data. An uncertain restore is protected. Saved content and Trash images remain; confirmed unreferenced leftover images can be removed through Cleanup.": "يؤدي ذلك إلى حذف بيانات النقل المؤقتة. تُحمى عمليات الاستعادة غير مؤكدة النتيجة. يبقى المحتوى المحفوظ وصور سلة المحذوفات، ويمكن حذف الصور المتبقية التي تأكد عدم استخدامها عبر أداة التنظيف.",
  "Review folder restore": "مراجعة الاستعادة من المجلد",
  "The previous outcome needs confirmation. Retry the same reviewed request without re-uploading.": "تحتاج النتيجة السابقة إلى تأكيد. أعد إرسال الطلب نفسه الذي راجعته دون رفع الملفات مجددًا.",
  "Every file is verified. Restore changes only the draft; the website changes after a separate publication.": "تم التحقق من كل ملف. تغيّر الاستعادة المسودة فقط، ويتغير الموقع عند نشرها لاحقًا.",
  "Confirm restore outcome": "تأكيد نتيجة الاستعادة",
  "Local workspace": "مساحة العمل المحلية",
  "VETRA staff": "فريق VETRA",
  "Your store, thoughtfully managed": "إدارة متجرك بكل عناية",
  "CMS access is not configured for this environment. Check the setup, then try again.": "لم يُضبط الوصول إلى نظام الإدارة في هذه البيئة. راجع الإعدادات ثم أعد المحاولة.",
  "Manage products, articles, and store details in this local preview.": "أدر المنتجات والمقالات وتفاصيل المتجر في هذه المعاينة المحلية.",
  "Sign in with your staff account.": "سجّل الدخول بحساب فريق العمل.",
  "Try again": "إعادة المحاولة",
  "Email": "البريد الإلكتروني",
  "Password": "كلمة المرور",
  "Signing in…": "جارٍ تسجيل الدخول…",
  "Enter local workspace": "الدخول إلى مساحة العمل المحلية",
  "Sign in": "تسجيل الدخول",
  "Product gallery": "معرض صور المنتج",
  "Add image": "إضافة صورة",
  "Arrange images in display order. The main product image is managed separately and is shown when the gallery is empty.": "رتّب الصور حسب ترتيب عرضها. تُدار صورة المنتج الرئيسية بصورة مستقلة وتُعرض إذا كان المعرض فارغًا.",
  "Image": "الصورة",
  "Move image up": "نقل الصورة إلى الأعلى",
  "Move image down": "نقل الصورة إلى الأسفل",
  "Remove image from gallery": "إزالة الصورة من المعرض",
  "Image description": "وصف الصورة",
  "Caption (optional)": "تعليق (اختياري)"
};
