import { commerceArabic } from "@/content/customer-ar";
import type { Localized } from "@/lib/i18n";

const en = {
  itemCount: "{count} {unit}",
  translatedDetailsNotice: "This product's details are available in another language.",
  availableCount: "{count} {unit} {available}",
  gram: "g",
  breadcrumb: "Breadcrumb",
  coffeeBeansAlt: "Coffee beans in a warm natural setting",
  coffeeRitualAlt: "A cup of coffee for an everyday ritual",
  coffeePauseAlt: "A quiet moment with a favourite cup of coffee",
  coffeeEyebrow: "FOR THE COFFEE MOMENTS",
  coffeeName: "Coffee beans",
  coffeeIntro: "Something good is still in the making.",
  instantEyebrow: "YOUR EVERYDAY RITUAL",
  instantName: "Instant coffee",
  instantIntro: "A new chapter in the collection, coming soon.",
  collectionNote: "Products and brands. Thoughtfully chosen.",
  ourStory: "About us",
  home: "Home",
  shop: "Our collection",
  products: "Products",
  honey: "Honey",
  coffee: "Coffee",
  all: "All products",
  comingSoon: "Coming soon",
  collectionEyebrow: "A considered collection",
  collectionTitle: "Good things, naturally.",
  collectionIntro:
    "Explore selected products and brands, with clear details to help you choose.",
  search: "Search the collection",
  searchPlaceholder: "Find something good…",
  clear: "Clear filters",
  result: "product",
  results: "products",
  available: "available",
  sort: "Sort by",
  featured: "Featured",
  priceLow: "Price: low to high",
  priceHigh: "Price: high to low",
  noResults: "No products in this category yet.",
  noResultsBody:
    "Clear your filters to explore the current selection, or search by product or brand name.",
  noSearch: "No products found",
  noSearchBody: "Try a product or brand name, or clear your filters to see the collection.",
  curated: "SELECTED BY VETRA",
  add: "Add to bag",
  added: "Added to your bag",
  viewBag: "View bag",
  fullBag: "You have reached the limit of 96 jars per enquiry.",
  save: "Save to favourites",
  saved: "Remove from favourites",
  quantity: "Quantity",
  decrease: "Decrease quantity",
  increase: "Increase quantity",
  size: "Size",
  oneJar: "one jar",
  productEyebrow: "ESHAN · NORTHERN THAILAND",
  productTagline: "A little sweetness. A moment to savour.",
  productOrigin:
    "From the flowers of northern Thailand’s coffee trees to a simple everyday ritual. ESHAN coffee blossom honey has just one ingredient: 100% coffee blossom honey.",
  ingredient: "One ingredient",
  ingredientValue: "100% coffee blossom honey",
  origin: "Northern Thailand",
  originValue: "Origin stated on the product label",
  storage: "Simply stored",
  storageValue: "Keep at room temperature",
  deliveryNote:
    "Shipping and payment arrangements are confirmed by our team. Adding to your bag does not place an order.",
  details: "The details",
  ingredients: "Ingredients & storage",
  use: "Everyday rituals",
  shipping: "Ordering & delivery",
  detailTitle: "From coffee blossoms, with care.",
  detailBody:
    "Coffee blossom honey is honey harvested from coffee blossoms. This ESHAN honey comes from the northern part of Thailand, as stated on its label. Each jar contains 380 g of 100% coffee blossom honey.",
  ingredientBody:
    "Ingredients: 100% coffee blossom honey. Storage: keep at room temperature. Please consult the label on the jar for its batch information and best-before date.",
  useBody:
    "Drizzle over warm toast, spoon into plain yoghurt, or stir into your favourite drink. Start with a little and adjust to taste.",
  shippingBody:
    "Online payment is not available yet. Shipping cost, delivery timing and payment arrangements must be confirmed before an order can be completed. For retail or wholesale enquiries, please contact our team.",
  editorialEyebrow: "SIMPLE PLEASURES",
  editorialTitle: "Make a little room\nfor something good.",
  editorialBody:
    "A slow morning. Your favourite cup. A spoonful of sweetness. Sometimes, the everyday things are the ones to treasure.",
  frontImage: "Original photograph of the ESHAN honey front label",
  backImage:
    "Original photograph of the ESHAN honey ingredients and storage label",
  lifestyleImage: "ESHAN Coffee Blossom Honey jar among coffee blossoms",
  imageLabel: "View image",
  reference: "Original product label",
  cartTitle: "Your bag",
  cartSubtitle: "Review your products and quantities before continuing.",
  emptyTitle: "Your bag is empty",
  emptyBody: "Explore our products and save your selection here.",
  browse: "View products",
  continue: "Continue shopping",
  remove: "Remove",
  cartUpdated: "Quantity updated. Product subtotal:",
  cartRemoved: "Product removed from your bag.",
  cartLocal: "Your bag is saved in this browser.",
  item: "item",
  items: "items",
  summary: "Your selection",
  subtotal: "Subtotal",
  delivery: "Delivery",
  toConfirm: "To be confirmed",
  estimated: "Product subtotal",
  exclShipping:
    "Shipping is not included. Final arrangements are confirmed before payment.",
  checkout: "Continue to checkout",
  loading: "Loading your selection…",
  checkoutTitle: "Review your selection",
  checkoutEyebrow: "CHECKOUT",
  shippingInfo: "Your details",
  fullName: "Full name",
  email: "Email address",
  phone: "Phone number",
  address: "Street address",
  district: "City / district",
  province: "State / region",
  country: "Country / region",
  postcode: "Postal / ZIP code",
  notes: "Note for our team (optional)",
  setupTitle: "Online ordering is not open yet.",
  setupBody:
    "We are finalising delivery and payment arrangements. Your bag is ready to return to when we open. For now, get in touch about your selection.",
  contact: "Contact our team",
  returnBag: "Back to your bag",
  enquiryTitle: "Send an order enquiry",
  enquiryBody:
    "This sends your selection and contact details to our team. It does not place a paid order or reserve stock. We will confirm availability, shipping and payment with you.",
  consent:
    "I agree to share these details so VETRA STORE can respond to this enquiry.",
  privacy: "Read our privacy notice",
  send: "Send order enquiry",
  sending: "Sending your enquiry…",
  error:
    "We could not save your enquiry. Your details are still here; please try again.",
  successTitle: "Your enquiry is with us.",
  successBody:
    "We have saved your selection and contact details. Our team will confirm availability and the next steps. No payment has been taken.",
  referenceLabel: "Enquiry reference",
  demoTitle: "Preview checkout",
  demoBody: "Try the complete flow with sample details. Records are saved only in this browser. No order, message or payment is sent.",
  demoConsent: "I understand this preview saves sample details in this browser only.",
  demoMethod: "Choose a preview",
  demoEnquiry: "Order enquiry",
  demoEnquiryDescription: "Preview a request for availability and shipping.",
  demoPayment: "Payment preview",
  demoPaymentDescription: "Simulate payment without entering card or bank details.",
  demoOutcome: "Simulated payment result",
  demoApproved: "Successful",
  demoDeclined: "Declined",
  demoShipping: "Shipping is still to be confirmed. The simulation uses the product subtotal only.",
  demoSend: "Save preview enquiry",
  demoPay: "Run payment preview",
  demoSaving: "Saving preview…",
  demoSuccessTitle: "Preview saved",
  demoSuccessBody: "Your selection and sample details are saved in this browser. No enquiry was sent and no payment was taken.",
  demoPaymentSuccess: "Payment success simulated",
  demoPaymentSuccessBody: "The preview is saved in this browser as a simulated successful payment. No real payment was taken or order placed.",
  demoFailureTitle: "Payment decline simulated",
  demoFailureBody: "This declined preview is saved in this browser. No payment was taken. Your details and bag are unchanged; choose Successful and try again.",
  demoStorageError: "The preview could not be saved. Check your details and browser storage, then try again. Your details are still here.",
  demoReference: "Preview reference",
  demoRetry: "Try payment again",
  demoNewPreview: "Create another preview",
  savedTitle: "Your little corner of VETRA.",
  savedEyebrow: "SAVED FOR LATER",
  savedIntro: "The things you love, kept close for another day.",
  savedLocal:
    "Favourites and your bag are saved in this browser. No account or sign-in is required.",
  favourites: "Your favourites",
  emptyFavourites: "Found something you love?",
  emptyFavouritesBody: "Tap the heart on a product to keep it here for later.",
  bagShortcut: "Visit your bag",
};
export const commerce: Localized<typeof en> = {
  ar: commerceArabic,
  en,
  th: {
    itemCount: "{count} {unit}",
    translatedDetailsNotice: "รายละเอียดสินค้านี้แสดงในภาษาอื่นที่มีข้อมูลครบถ้วน",
    availableCount: "{count} {unit} {available}",
    gram: "กรัม",
    breadcrumb: "เส้นทางนำทาง",
    coffeeBeansAlt: "เมล็ดกาแฟในบรรยากาศอบอุ่น",
    coffeeRitualAlt: "ถ้วยกาแฟสำหรับช่วงเวลาในทุกวัน",
    coffeePauseAlt: "ช่วงเวลาพักกับกาแฟแก้วโปรด",
    coffeeEyebrow: "สำหรับคนรักกาแฟ",
    coffeeName: "เมล็ดกาแฟ",
    coffeeIntro: "เรากำลังคัดสรรสิ่งดี ๆ เพิ่มเติมให้คุณ",
    instantEyebrow: "ความสุขในทุกวัน",
    instantName: "กาแฟสำเร็จรูป",
    instantIntro: "คอลเลกชันถัดไปกำลังเริ่มต้น",
    collectionNote: "สินค้าและแบรนด์ที่คัดสรรด้วยความใส่ใจ",
    ourStory: "เกี่ยวกับเรา",
    home: "หน้าหลัก",
    shop: "คอลเลกชันของเรา",
    products: "สินค้า",
    honey: "น้ำผึ้ง",
    coffee: "กาแฟ",
    all: "สินค้าทั้งหมด",
    comingSoon: "เร็ว ๆ นี้",
    collectionEyebrow: "คัดสรรด้วยความใส่ใจ",
    collectionTitle: "สิ่งดี ๆ จากธรรมชาติ",
    collectionIntro:
      "เลือกชมสินค้าและแบรนด์ที่คัดสรร พร้อมรายละเอียดที่ช่วยให้คุณเลือกได้ง่ายขึ้น",
    search: "ค้นหาในคอลเลกชัน",
    searchPlaceholder: "ค้นหาสิ่งดี ๆ ที่คุณมองหา…",
    clear: "ล้างตัวกรอง",
    result: "รายการ",
    results: "รายการ",
    available: "พร้อมจำหน่าย",
    sort: "เรียงตาม",
    featured: "สินค้าแนะนำ",
    priceLow: "ราคา: ต่ำไปสูง",
    priceHigh: "ราคา: สูงไปต่ำ",
    noResults: "ยังไม่มีสินค้าในหมวดนี้",
    noResultsBody:
      "ล้างตัวกรองเพื่อดูสินค้าที่แสดงอยู่ หรือค้นหาด้วยชื่อสินค้าหรือแบรนด์",
    noSearch: "ไม่พบสินค้าที่ค้นหา",
    noSearchBody: "ลองค้นหาด้วยชื่อสินค้าหรือแบรนด์ หรือล้างตัวกรองเพื่อดูสินค้าทั้งหมด",
    curated: "คัดสรรโดย VETRA",
    add: "เพิ่มลงตะกร้า",
    added: "เพิ่มลงตะกร้าแล้ว",
    viewBag: "ดูตะกร้า",
    fullBag: "เพิ่มได้สูงสุด 96 ขวดต่อการสอบถามหนึ่งครั้ง",
    save: "บันทึกเป็นรายการโปรด",
    saved: "นำออกจากรายการโปรด",
    quantity: "จำนวน",
    decrease: "ลดจำนวน",
    increase: "เพิ่มจำนวน",
    size: "ขนาด",
    oneJar: "หนึ่งกระปุก",
    productEyebrow: "อิชาน · ภาคเหนือของประเทศไทย",
    productTagline: "เติมความหวาน ให้ช่วงเวลาดี ๆ",
    productOrigin:
      "จากดอกกาแฟในภาคเหนือของไทย สู่ช่วงเวลาเรียบง่ายในทุกวัน น้ำผึ้งดอกกาแฟตราอิชาน มีส่วนประกอบเพียงอย่างเดียวคือน้ำผึ้งดอกกาแฟ 100%",
    ingredient: "ส่วนประกอบเดียว",
    ingredientValue: "น้ำผึ้งดอกกาแฟ 100%",
    origin: "จากภาคเหนือของไทย",
    originValue: "ข้อมูลแหล่งที่มาตามฉลากสินค้า",
    storage: "เก็บรักษาง่าย",
    storageValue: "เก็บไว้ที่อุณหภูมิห้อง",
    deliveryNote:
      "จัดส่งฟรีในประเทศไทย ทีมงานจะยืนยันพื้นที่จัดส่งและการชำระเงิน การเพิ่มลงตะกร้ายังไม่ถือเป็นการสั่งซื้อ",
    details: "รายละเอียดสินค้า",
    ingredients: "ส่วนประกอบและการเก็บรักษา",
    use: "ไอเดียในทุกวัน",
    shipping: "การสั่งซื้อและจัดส่ง",
    detailTitle: "ความหวานจากดอกกาแฟ",
    detailBody:
      "น้ำผึ้งดอกกาแฟ คือน้ำผึ้งที่เก็บจากดอกของต้นกาแฟ น้ำผึ้งตราอิชานมีแหล่งที่มาจากภาคเหนือของประเทศไทยตามข้อมูลบนฉลาก แต่ละกระปุกบรรจุน้ำผึ้งดอกกาแฟ 100% น้ำหนักสุทธิ 380 กรัม",
    ingredientBody:
      "ส่วนประกอบ: น้ำผึ้งดอกกาแฟ 100% วิธีเก็บรักษา: เก็บไว้ที่อุณหภูมิห้อง โปรดดูข้อมูลรุ่นการผลิตและวันหมดอายุบนฉลากของกระปุกที่ได้รับ",
    useBody:
      "เติมบนขนมปังอุ่น ๆ ตักใส่โยเกิร์ตรสธรรมชาติ หรือผสมในเครื่องดื่มแก้วโปรด เริ่มทีละน้อยแล้วปรับความหวานตามชอบ",
    shippingBody:
      "จัดส่งฟรีในประเทศไทย ยังไม่เปิดรับชำระเงินออนไลน์ ทีมงานจะยืนยันพื้นที่ ระยะเวลาจัดส่ง และวิธีชำระเงินก่อนดำเนินการ ติดต่อทีมงานสำหรับการซื้อปลีกหรือซื้อส่ง",
    editorialEyebrow: "ความสุขที่เรียบง่าย",
    editorialTitle: "เผื่อเวลาเล็กน้อย\nให้สิ่งดี ๆ ในทุกวัน",
    editorialBody:
      "เช้าที่ไม่เร่งรีบ เครื่องดื่มแก้วโปรด และความหวานอีกสักนิด บางครั้งสิ่งธรรมดาในทุกวันก็คือสิ่งที่น่าจดจำที่สุด",
    frontImage: "ภาพจริงของฉลากด้านหน้าน้ำผึ้งอิชาน",
    backImage: "ภาพจริงของฉลากส่วนประกอบและการเก็บรักษาน้ำผึ้งอิชาน",
    lifestyleImage: "น้ำผึ้งดอกกาแฟ ESHAN ท่ามกลางดอกกาแฟ",
    imageLabel: "ดูภาพ",
    reference: "ฉลากสินค้าจริง",
    cartTitle: "ตะกร้าของคุณ",
    cartSubtitle: "ตรวจสอบสินค้าและจำนวนก่อนดำเนินการต่อ",
    emptyTitle: "ยังไม่มีสินค้าในตะกร้า",
    emptyBody: "เลือกชมสินค้าและบันทึกรายการที่คุณสนใจไว้ที่นี่",
    browse: "เลือกชมสินค้า",
    continue: "เลือกซื้อสินค้าต่อ",
    remove: "นำออก",
    cartUpdated: "อัปเดตจำนวนแล้ว ยอดรวมสินค้า:",
    cartRemoved: "นำสินค้าออกจากตะกร้าแล้ว",
    cartLocal: "ตะกร้าของคุณบันทึกไว้ในเบราว์เซอร์นี้",
    item: "ชิ้น",
    items: "ชิ้น",
    summary: "สรุปสินค้าที่เลือก",
    subtotal: "ยอดรวมสินค้า",
    delivery: "การจัดส่ง",
    toConfirm: "รอยืนยัน",
    estimated: "ยอดรวมสินค้า",
    exclShipping: "จัดส่งฟรีในประเทศไทย ทีมงานจะยืนยันพื้นที่จัดส่งและการชำระเงิน",
    checkout: "ดำเนินการต่อ",
    loading: "กำลังโหลดสินค้าที่เลือก…",
    checkoutTitle: "ตรวจสอบรายการสินค้า",
    checkoutEyebrow: "ข้อมูลการสั่งซื้อ",
    shippingInfo: "ข้อมูลของคุณ",
    fullName: "ชื่อและนามสกุล",
    email: "อีเมล",
    phone: "หมายเลขโทรศัพท์",
    address: "ที่อยู่",
    district: "เขต / อำเภอ",
    province: "จังหวัด",
    country: "ประเทศ / ภูมิภาค",
    postcode: "รหัสไปรษณีย์",
    notes: "ข้อความถึงทีมงาน (ไม่บังคับ)",
    setupTitle: "ยังไม่เปิดรับคำสั่งซื้อออนไลน์",
    setupBody:
      "เรากำลังเตรียมรายละเอียดการจัดส่งและการชำระเงิน ตะกร้าของคุณจะยังอยู่เมื่อกลับมาอีกครั้ง ระหว่างนี้สามารถติดต่อสอบถามสินค้าที่สนใจได้",
    contact: "ติดต่อทีมงาน",
    returnBag: "กลับไปที่ตะกร้า",
    enquiryTitle: "ส่งคำสอบถามสินค้า",
    enquiryBody:
      "ส่งรายการสินค้าและข้อมูลติดต่อให้ทีมงาน ยังไม่ถือเป็นการสั่งซื้อ ชำระเงิน หรือจองสินค้า ทีมงานจะยืนยันสินค้าที่พร้อมจำหน่าย พื้นที่จัดส่ง และวิธีชำระเงินกับคุณ",
    consent:
      "ฉันยินยอมให้ VETRA STORE ใช้ข้อมูลเหล่านี้เพื่อตอบกลับคำสอบถามนี้",
    privacy: "อ่านนโยบายความเป็นส่วนตัว",
    send: "ส่งคำสอบถามสินค้า",
    sending: "กำลังส่งคำสอบถาม…",
    error: "ไม่สามารถบันทึกคำสอบถามได้ ข้อมูลของคุณยังอยู่ กรุณาลองอีกครั้ง",
    successTitle: "ได้รับคำสอบถามของคุณแล้ว",
    successBody:
      "เราบันทึกรายการสินค้าและข้อมูลติดต่อแล้ว ทีมงานจะยืนยันสินค้าที่พร้อมจำหน่ายและขั้นตอนถัดไป ยังไม่มีการเรียกเก็บเงิน",
    referenceLabel: "หมายเลขอ้างอิง",
    demoTitle: "ทดลองขั้นตอนสั่งซื้อ",
    demoBody: "ทดลองด้วยข้อมูลตัวอย่าง รายการจะบันทึกเฉพาะในเบราว์เซอร์นี้ ไม่มีการส่งคำสั่งซื้อ ข้อความ หรือชำระเงินจริง",
    demoConsent: "ฉันเข้าใจว่าการทดลองนี้จะบันทึกข้อมูลตัวอย่างเฉพาะในเบราว์เซอร์นี้",
    demoMethod: "เลือกรูปแบบการทดลอง",
    demoEnquiry: "สอบถามสินค้า",
    demoEnquiryDescription: "ทดลองส่งคำสอบถามสินค้าและการจัดส่ง",
    demoPayment: "ทดลองชำระเงิน",
    demoPaymentDescription: "จำลองการชำระเงิน โดยไม่ต้องกรอกข้อมูลบัตรหรือบัญชีธนาคาร",
    demoOutcome: "ผลการชำระเงินจำลอง",
    demoApproved: "สำเร็จ",
    demoDeclined: "ไม่สำเร็จ",
    demoShipping: "จัดส่งฟรีในประเทศไทยเมื่อระบุรหัสไปรษณีย์ไทย 5 หลัก การทดลองนี้ไม่มีการจัดส่งจริง",
    demoSend: "บันทึกคำสอบถามตัวอย่าง",
    demoPay: "ทดลองชำระเงิน",
    demoSaving: "กำลังบันทึกตัวอย่าง…",
    demoSuccessTitle: "บันทึกตัวอย่างแล้ว",
    demoSuccessBody: "รายการสินค้าและข้อมูลตัวอย่างบันทึกไว้ในเบราว์เซอร์นี้ ไม่มีการส่งคำสอบถามหรือเรียกเก็บเงิน",
    demoPaymentSuccess: "จำลองการชำระเงินสำเร็จแล้ว",
    demoPaymentSuccessBody: "บันทึกตัวอย่างพร้อมสถานะชำระเงินจำลองสำเร็จไว้ในเบราว์เซอร์นี้ ไม่มีการชำระเงินจริงหรือส่งคำสั่งซื้อ",
    demoFailureTitle: "จำลองการชำระเงินไม่สำเร็จ",
    demoFailureBody: "บันทึกตัวอย่างที่ชำระเงินไม่สำเร็จไว้ในเบราว์เซอร์นี้ ไม่มีการเรียกเก็บเงิน ข้อมูลและตะกร้าของคุณยังอยู่ เลือกสำเร็จแล้วลองอีกครั้งได้",
    demoStorageError: "ไม่สามารถบันทึกตัวอย่างได้ ตรวจสอบข้อมูลและการจัดเก็บในเบราว์เซอร์แล้วลองอีกครั้ง ข้อมูลที่กรอกยังอยู่",
    demoReference: "หมายเลขตัวอย่าง",
    demoRetry: "ทดลองชำระเงินอีกครั้ง",
    demoNewPreview: "สร้างตัวอย่างใหม่",
    savedTitle: "มุมเล็ก ๆ ของคุณที่ VETRA",
    savedEyebrow: "เก็บไว้สำหรับวันหน้า",
    savedIntro: "สิ่งที่คุณชอบ เก็บไว้ใกล้ตัวเพื่อกลับมาพบกันอีกครั้ง",
    savedLocal:
      "รายการโปรดและตะกร้าบันทึกไว้ในเบราว์เซอร์นี้ ไม่ต้องสมัครสมาชิกหรือเข้าสู่ระบบ",
    favourites: "รายการโปรดของคุณ",
    emptyFavourites: "เจอสิ่งที่ถูกใจแล้วหรือยัง",
    emptyFavouritesBody: "แตะหัวใจบนสินค้าเพื่อบันทึกไว้ที่นี่สำหรับวันหน้า",
    bagShortcut: "ไปที่ตะกร้า",
  },
};
