import { mockCheckoutArabic } from "@/content/customer-ar";
import type { Localized } from "@/lib/i18n";
const en = {
  settings: "Shipping and stock simulation", note: "Browser-only test settings. No real shipping prices, stock changes, charges or carrier services are created.", rules: "Simulated shipping rules", empty: "No rules configured. Shipping remains unconfirmed.", add: "Add test rule", remove: "Remove rule", label: "Rule name", prefix: "Postcode prefix", prefixHint: "Use 1–5 digits, or * for all other five-digit postcodes. The most specific matching rule wins.", fee: "Test fee (THB)", freeOver: "Free above subtotal (THB, optional)", save: "Save simulation settings", saved: "Simulation settings saved", failed: "Could not save. Use unique postcode prefixes, a name, and valid amounts. Your input is preserved.", stock: "Simulated stock availability", stockNote: "Uses published stock as the starting quantity. Unconfirmed stock stays unknown. Failed payment attempts reserve stock for 15 minutes; successful payments commit it. Cancel or refund before shipment to release it. Deleting a request does not release committed stock.", unknown: "Unconfirmed", units: "units available", shipping: "Simulated shipping", total: "Simulated total", quoted: "Test quote saved with this order", pending: { unconfigured: "Shipping simulation is not configured", "destination-missing": "Enter a five-digit postcode to preview shipping", unsupported: "No test shipping rule matches this postcode" }, pendingNote: "Only the product subtotal is shown. Shipping still needs confirmation.", quoteNote: "Test amount only. Saved orders keep their original quote when rules change.", inventory: "Stock simulation", inventoryStates: { reserved: "Reserved for payment retry", committed: "Committed to this simulated order", released: "Released", untracked: "No reservation" }, expires: "Reservation expires", restock: "Returned items received: release simulated stock", restockNote: "A refund after shipment does not automatically return stock. Confirm this only when testing a received return.", stockError: "Not enough stock remains for this simulation. Review stock and existing reservations, then try again. Your input is preserved.",
};
export const mockCheckoutCopy: Localized<typeof en> = {
  ar: mockCheckoutArabic, en, th: {
  settings: "จำลองการจัดส่งและสต็อก", note: "ตั้งค่าทดสอบในเบราว์เซอร์นี้เท่านั้น ไม่สร้างค่าจัดส่งจริง เปลี่ยนสต็อกจริง เรียกเก็บเงิน หรือติดต่อขนส่ง", rules: "เงื่อนไขค่าจัดส่งจำลอง", empty: "ยังไม่ตั้งค่าเงื่อนไข ค่าจัดส่งยังต้องยืนยัน", add: "เพิ่มเงื่อนไขทดสอบ", remove: "ลบเงื่อนไข", label: "ชื่อเงื่อนไข", prefix: "รหัสไปรษณีย์ขึ้นต้นด้วย", prefixHint: "ใส่ตัวเลข 1–5 หลัก หรือ * สำหรับรหัสไปรษณีย์ 5 หลักอื่น ๆ ใช้เงื่อนไขที่ตรงละเอียดที่สุดก่อน", fee: "ค่าจัดส่งทดสอบ (บาท)", freeOver: "จัดส่งฟรีเมื่อยอดสินค้าถึง (บาท ไม่บังคับ)", save: "บันทึกการตั้งค่าจำลอง", saved: "บันทึกการตั้งค่าจำลองแล้ว", failed: "บันทึกไม่สำเร็จ กรุณาตรวจสอบชื่อ จำนวนเงิน และรหัสไปรษณีย์ที่ไม่ซ้ำกัน ข้อมูลที่กรอกยังอยู่", stock: "สต็อกคงเหลือจำลอง", stockNote: "ใช้สต็อกที่เผยแพร่เป็นจำนวนเริ่มต้น หากยังไม่ยืนยันจะแสดงว่าไม่ทราบ การชำระไม่สำเร็จจะจองสินค้า 15 นาที ชำระสำเร็จจะตัดสต็อกจำลอง ยกเลิกหรือคืนเงินก่อนจัดส่งเพื่อคืนสต็อก การลบคำขอไม่คืนสต็อกที่ตัดแล้ว", unknown: "ยังไม่ยืนยัน", units: "ชิ้นคงเหลือ", shipping: "ค่าจัดส่งจำลอง", total: "ยอดรวมจำลอง", quoted: "บันทึกค่าจัดส่งทดสอบไว้กับรายการนี้แล้ว", pending: { unconfigured: "ยังไม่ตั้งค่าจัดส่งจำลอง", "destination-missing": "กรอกรหัสไปรษณีย์ไทย 5 หลักเพื่อแสดงการจัดส่งฟรีภายในประเทศไทย", unsupported: "ไม่มีเงื่อนไขจัดส่งทดสอบที่ตรงกับรหัสไปรษณีย์นี้" }, pendingNote: "ยังไม่ระบุรหัสไปรษณีย์สำหรับการจัดส่งฟรีภายในประเทศไทย", quoteNote: "จำนวนเงินทดสอบเท่านั้น ไม่มีการจัดส่งหรือเรียกเก็บเงินจริง", inventory: "สต็อกจำลอง", inventoryStates: { reserved: "จองไว้เพื่อลองชำระอีกครั้ง", committed: "ตัดสต็อกสำหรับรายการจำลองนี้แล้ว", released: "คืนสต็อกแล้ว", untracked: "ไม่มีการจอง" }, expires: "การจองหมดอายุ", restock: "ได้รับสินค้าคืนแล้ว: คืนสต็อกจำลอง", restockNote: "การคืนเงินหลังจัดส่งไม่คืนสต็อกอัตโนมัติ ยืนยันเมื่อทดสอบกรณีได้รับสินค้าคืนแล้วเท่านั้น", stockError: "สต็อกสำหรับการจำลองนี้ไม่เพียงพอ กรุณาตรวจสอบสต็อกและรายการที่จองไว้ แล้วลองอีกครั้ง ข้อมูลที่กรอกยังอยู่",
} };
