import type { Localized } from "@/lib/i18n";
import { storeDetails } from "@/content/store-details";

export const editorialUi = {
  ar: {
    honeyImageAlt: "عبوة عسل أزهار القهوة من ESHAN بين أزهار القهوة",
    exploreCollection: "تصفّح المنتجات",
    helpTopics: "مواضيع المساعدة",
    backToJournal: "العودة إلى المقالات",
    honeyCtaDescription: "اكتشف عسل أزهار القهوة من ESHAN، بوزن 380 غرامًا.",
    meetHoney: "اكتشف العسل",
  },
  th: {
    honeyImageAlt: "น้ำผึ้งดอกกาแฟ ESHAN ท่ามกลางดอกกาแฟ",
    exploreCollection: "เลือกชมสินค้า",
    helpTopics: "หัวข้อช่วยเหลือ",
    backToJournal: "กลับไปยังบทความ",
    honeyCtaDescription: "รู้จักน้ำผึ้งดอกกาแฟ ESHAN ขนาด 380 กรัม",
    meetHoney: "ดูสินค้า",
  },
  en: {
    honeyImageAlt: "ESHAN Coffee Blossom Honey jar among coffee blossoms",
    exploreCollection: "Explore the collection",
    helpTopics: "Help topics",
    backToJournal: "Back to articles",
    honeyCtaDescription: "Explore ESHAN Coffee Blossom Honey, 380 g.",
    meetHoney: "Meet the honey",
  },
} satisfies Localized<Record<string, string>>;

export const storyCopy = {
  ar: {
    title: "من نحن",
    description: "تعرّف على VETRA STORE ونهجنا في اختيار منتجات تجمع بين الجودة والاستخدام اليومي والقيمة.",
    eyebrow: "من اختيار VETRA",
    hero: "منتجات عالية الجودة.\nوقيمة استثنائية.",
    subtitle: "نختار بعناية، لتختار بثقة.",
    why: "من اختيار VETRA",
    heading: "الاختيار الجيد\nيبدأ بالفهم.",
    body: "تتخصص VETRA في اختيار المنتجات وفق معايير عالية، مع الاهتمام بالجودة والقيمة.",
    body2: "ندرس المنتجات ومنشأها وطرق استخدامها. ونقدّم تفاصيل واضحة تساعدك على اختيار ما يناسبك أو يناسب متجرك ونشاطك التجاري.",
    shop: "منتجاتنا",
    values: [
      { title: "معرفة المنتج", text: "ندرس المكوّنات والمنشأ وطرق الاستخدام العملية لنعرف جيدًا المنتجات التي نختارها لك." },
      { title: "الجودة أولًا", text: "ننظر إلى التفاصيل المهمة لكل منتج، مع التركيز على المعايير ومدى ملاءمته للاستخدام اليومي." },
      { title: "القيمة في كل تفصيل", text: "الجودة والكمية والسعر والفائدة عناصر مترابطة. ننظر إليها معًا عند اختيار منتجاتنا." },
    ],
    quote: "منتجات عالية الجودة.\nوقيمة مدروسة.",
    quoteSub: "من اختيار VETRA STORE.",
    note: "صور تعبيرية تجسّد رؤية العلامة.",
    heroImageAlt: "صورة توضيحية لعسل يُضاف إلى فنجان قهوة في ضوء الصباح",
    imageCaption: "عناية بتفاصيل الحياة اليومية",
    principlesEyebrow: "ما نهتم به",
    principlesTitle: "اختيار عن معرفة.\nواهتمام بالجودة والقيمة.",
    principlesIntro: "المنتج الجيد يحمل تفاصيل تتجاوز الانطباع الأول. نمنحها وقتها قبل أن نقدّمه لك.",
    processEyebrow: "نهج VETRA",
    processTitle: "ندرس التفاصيل.\nلنجعل الاختيار أسهل.",
    processIntro: "يبدأ اختيارنا بفهم المنتج، وينتهي بمعلومات واضحة تساعدك على اتخاذ قرارك.",
    processSteps: [
      { title: "الدراسة والفهم", text: "نتعرّف على المنتج ومنشئه وخصائصه لفهم طرق استخدامه." },
      { title: "الاهتمام بما يهم", text: "نراجع المكوّنات وبيانات الملصق والجودة والكمية والسعر، بحسب طبيعة كل منتج." },
      { title: "تقديم معلومات واضحة", text: "نقدّم تفاصيل وإرشادات مفيدة عن المنتج، مع المساعدة قبل البيع وبعده." },
    ],
    serviceEyebrow: "اختيارات تناسبك",
    serviceTitle: "لحياتك اليومية.\nولنشاطك التجاري.",
    serviceIntro: "سواء كنت تشتري لنفسك أو تختار لمتجرك، نساعدك على فهم المنتجات والعثور على ما يلائم احتياجاتك.",
    services: [
      { title: "لحياتك اليومية", text: "تصفّح تفاصيل المنتجات واستخداماتها وأسعارها. تواصل معنا إذا احتجت إلى معلومات إضافية قبل الاختيار." },
      { title: "للمتاجر وقطاع الأعمال", text: "تحدث معنا عن المنتجات والكميات وطلبات الجملة ليتحقق فريقنا من التفاصيل المناسبة لنشاطك." },
    ],
    contact: "تحدث إلى فريق VETRA",
    closingEyebrow: "من اختيار VETRA",
    closingTitle: "الأشياء الجميلة تبدأ\nباختيار مدروس.",
    closingBody: "اكتشف مختاراتنا، مع تفاصيل واضحة تساعدك على اتخاذ قرارك بنفسك.",
  },
  th: {
    title: "เกี่ยวกับเรา",
    description: "รู้จัก VETRA STORE และแนวคิดการคัดเลือกสินค้าที่ให้ความสำคัญกับคุณภาพ การใช้งาน และความคุ้มค่า",
    eyebrow: "VETRA คัดเลือก",
    hero: "สินค้าคุณภาพดี\nคุ้มค่ามากที่สุด",
    subtitle: "เราเลือกอย่างใส่ใจ เพื่อให้คุณเลือกได้อย่างมั่นใจ",
    why: "VETRA คัดเลือก",
    heading: "การเลือกที่ดี\nเริ่มจากความเข้าใจ",
    body: "VETRA เชี่ยวชาญการคัดเลือกสินค้า มาตรฐานสูง ให้ความสำคัญกับคุณภาพ และความคุ้มค่า",
    body2:
      "เราศึกษาสินค้า แหล่งที่มา และการใช้งาน พร้อมนำเสนอรายละเอียดที่ชัดเจน เพื่อให้คุณเลือกสิ่งที่เหมาะกับตัวเอง ร้านค้า หรือธุรกิจ",
    shop: "สินค้าของเรา",
    values: [
      {
        title: "รู้จักสินค้าจริง",
        text: "เราศึกษาสินค้าอย่างละเอียด ตั้งแต่ส่วนประกอบ แหล่งที่มา ไปจนถึงการใช้งาน เพื่อเข้าใจสิ่งที่เราเลือกมาให้คุณ",
      },
      {
        title: "ให้คุณภาพเป็นหลัก",
        text: "เราพิจารณารายละเอียดที่สำคัญกับสินค้าแต่ละประเภท ให้ความสำคัญกับมาตรฐานและความเหมาะสมกับการใช้งานจริง",
      },
      {
        title: "มองความคุ้มค่าให้ครบ",
        text: "เรามองทั้งคุณภาพ ปริมาณ ราคา และประโยชน์ที่ได้รับ เพื่อให้สินค้าที่เลือกมีคุณค่าในทุกวัน",
      },
    ],
    quote: "รวมสินค้าคุณภาพดี\nและคุ้มค่า",
    quoteSub: "คัดเลือกโดย VETRA STORE",
    note: "ภาพบรรยากาศประกอบแนวคิดของแบรนด์",
    heroImageAlt: "ภาพประกอบน้ำผึ้งที่เติมในถ้วยกาแฟ ท่ามกลางแสงเช้า",
    imageCaption: "ใส่ใจในรายละเอียดของทุกวัน",
    principlesEyebrow: "สิ่งที่เราให้ความสำคัญ",
    principlesTitle: "คัดเลือกด้วยความเข้าใจ\nใส่ใจทั้งคุณภาพและความคุ้มค่า",
    principlesIntro: "สินค้าที่ดีมีรายละเอียดมากกว่าที่เห็น เราจึงให้เวลากับสิ่งที่สำคัญ ก่อนนำมาให้คุณเลือก",
    processEyebrow: "แนวทางของ VETRA",
    processTitle: "มองให้รอบด้าน\nก่อนส่งต่อให้คุณ",
    processIntro: "การคัดเลือกของเราเริ่มจากการทำความเข้าใจสินค้า และจบด้วยข้อมูลที่ช่วยให้คุณตัดสินใจได้ง่ายขึ้น",
    processSteps: [
      { title: "ศึกษาและทำความเข้าใจ", text: "รู้จักสินค้า แหล่งที่มา และลักษณะเฉพาะ เพื่อเข้าใจว่าเหมาะกับการใช้งานแบบไหน" },
      { title: "พิจารณารายละเอียดสำคัญ", text: "ดูส่วนประกอบ ข้อมูลบนฉลาก คุณภาพ ปริมาณ และราคา โดยพิจารณาตามประเภทของสินค้า" },
      { title: "นำเสนออย่างชัดเจน", text: "รวบรวมข้อมูลสินค้าและคำแนะนำที่จำเป็น พร้อมให้คำปรึกษาก่อนและหลังการขาย" },
    ],
    serviceEyebrow: "เลือกให้เหมาะกับคุณ",
    serviceTitle: "เพื่อคุณ\nและธุรกิจของคุณ",
    serviceIntro: "ไม่ว่าจะเลือกซื้อใช้เอง หรือมองหาสินค้าสำหรับร้านค้า เราพร้อมช่วยให้คุณเข้าใจสินค้าและเลือกได้ตรงกับความต้องการ",
    services: [
      { title: "สำหรับทุกวันของคุณ", text: "ดูรายละเอียดสินค้า วิธีใช้ และราคาได้อย่างชัดเจน หากมีคำถาม เราพร้อมช่วยให้ข้อมูลก่อนเลือกซื้อ" },
      { title: "สำหรับร้านค้าและธุรกิจ", text: "ปรึกษาเรื่องสินค้า จำนวน และการสั่งซื้อขายส่ง เพื่อให้ทีมงานช่วยตรวจสอบรายละเอียดที่เหมาะกับธุรกิจของคุณ" },
    ],
    contact: "ปรึกษาทีม VETRA",
    closingEyebrow: "คัดเลือกโดย VETRA",
    closingTitle: "สิ่งดี ๆ\nเริ่มจากการเลือกที่ใส่ใจ",
    closingBody: "ค้นพบสินค้าที่เราเลือกมาให้ พร้อมรายละเอียดที่ช่วยให้คุณตัดสินใจได้ด้วยตัวเอง",
  },
  en: {
    title: "About us",
    description: "Meet VETRA STORE and our approach to selecting products for quality, everyday use, and value.",
    eyebrow: "SELECTED BY VETRA",
    hero: "Quality products.\nExceptional value.",
    subtitle: "Selected with care, so you can choose with confidence.",
    why: "SELECTED BY VETRA",
    heading: "Good choices begin\nwith understanding.",
    body: "VETRA specialises in selecting products to high standards, with a focus on quality and value.",
    body2:
      "We study products, their origins, and how they are used. Clear details help you choose what suits you, your shop, or your business.",
    shop: "Our products",
    values: [
      {
        title: "Know the product",
        text: "We study ingredients, origins, and practical use to understand the products we select for you.",
      },
      {
        title: "Quality comes first",
        text: "We consider the details that matter for each product, with a focus on standards and suitability for everyday use.",
      },
      {
        title: "Value in every detail",
        text: "Quality, quantity, price, and usefulness all matter. We consider them together when choosing our products.",
      },
    ],
    quote: "Quality products.\nConsidered value.",
    quoteSub: "Selected by VETRA STORE.",
    note: "Atmospheric imagery illustrating the brand’s philosophy.",
    heroImageAlt: "Illustration of honey being added to a cup of coffee in morning light",
    imageCaption: "Care in the everyday details",
    principlesEyebrow: "WHAT MATTERS TO US",
    principlesTitle: "Selected with understanding.\nChosen for quality and value.",
    principlesIntro: "There is more to a good product than first impressions. We take time to consider the details before bringing it to you.",
    processEyebrow: "THE VETRA APPROACH",
    processTitle: "Consider every detail.\nThen make choosing easier.",
    processIntro: "Our selection starts with understanding the product and leads to clear information that helps you decide.",
    processSteps: [
      { title: "Study and understand", text: "Explore the product, its origins, and its characteristics to understand how it can be used." },
      { title: "Consider what matters", text: "Look at ingredients, label information, quality, quantity, and price, with the product category in mind." },
      { title: "Share clear information", text: "Present useful product details and guidance, with help available before and after the sale." },
    ],
    serviceEyebrow: "CHOSEN TO SUIT YOU",
    serviceTitle: "For your everyday.\nFor your business.",
    serviceIntro: "Whether you are buying for yourself or choosing for your shop, we are here to help you understand the products and find what suits your needs.",
    services: [
      { title: "For your everyday", text: "Explore product details, uses, and prices. Ask us if you need more information before making your choice." },
      { title: "For shops and businesses", text: "Talk to us about products, quantities, and wholesale orders so our team can check the details for your business." },
    ],
    contact: "Talk to VETRA",
    closingEyebrow: "SELECTED BY VETRA",
    closingTitle: "Good things begin\nwith a considered choice.",
    closingBody: "Discover our selection, with clear details to help you make your own choice.",
  },
} satisfies Localized<unknown>;

export const journalCopy = {
  ar: {
    title: "مقالات وأدلة لاختيار المنتجات",
    description: "أدلة عملية من VETRA لاختيار المنتجات وقراءة الملصقات ومقارنة الجودة والقيمة، والاستمتاع بعسل أزهار القهوة والتخطيط لمشتريات الأعمال.",
    eyebrow: "من اختيار VETRA",
    heading: "معرفة أوضح.\nواختيار أفضل.",
    subtitle: "تتخصص VETRA في اختيار المنتجات وفق معايير عالية، مع الاهتمام بالجودة والقيمة.",
    latest: "تصفّح المقالات",
    count: "معرفة تساعدك على حسن الاختيار",
    read: "اقرأ المقال",
    featured: "مختارات VETRA",
    libraryIntro: "من تفاصيل الملصق إلى مكان المنتج في يومك، اكتشف إرشادات عملية تساعدك على الاختيار بعناية.",
    all: "جميع المقالات",
    categories: "تصنيفات المقالات",
    search: "ابحث في المقالات",
    searchPlaceholder: "جرّب البحث عن العسل أو الجودة أو الجملة",
    clear: "مسح البحث",
    results: "عدد المقالات المطابقة: {count}",
    noResults: "لا توجد مقالات تطابق بحثك",
    noResultsBody: "جرّب عبارة أقصر أو تصفّح جميع التصنيفات.",
    reset: "عرض جميع المقالات",
    minutes: "مدة القراءة: {minutes} دقيقة",
    approachEyebrow: "رؤية VETRA",
    approachTitle: "منتجات عالية الجودة.\nوقيمة استثنائية.",
    approachBody: "يبدأ الاختيار المدروس بالأسئلة المناسبة. تعرّف على مكوّنات المنتج ومدى ملاءمته لاحتياجاتك والقيمة التي يقدّمها مع الاستخدام.",
    approachLink: "نهجنا في الاختيار",
    principles: [
      { title: "افهم المنتج", text: "اقرأ المكوّنات والمنشأ والتفاصيل القابلة للتحقق قبل الحكم على المنتج من صوره أو إعلاناته." },
      { title: "اختر لما تحتاجه فعلًا", text: "اختر الحجم والشكل وطريقة العناية التي تناسب روتينك اليومي أو احتياجات نشاطك التجاري." },
      { title: "انظر إلى القيمة كاملة", text: "قارن الجودة والكمية التي ستستخدمها فعلًا والتكلفة الإجمالية معًا." },
    ],
    faqEyebrow: "قبل أن تختار",
    faqTitle: "أسئلة مفيدة لاختيار أوضح",
    questions: [
      { question: "من أين أبدأ عند اختيار منتج؟", answer: "ابدأ بطريقة الاستخدام والكمية التي تحتاجها، ثم راجع المكوّنات والحجم والمنشأ وتعليمات الحفظ. يسهل ذلك مقارنة المنتجات على أساس واحد." },
      { question: "هل السعر الأقل هو دائمًا القيمة الأفضل؟", answer: "السعر أحد عناصر القيمة. انظر إلى تكلفة الوحدة والكمية التي ستستخدمها فعلًا ومدى ملاءمة المنتج لاحتياجاتك. قد تكون تكلفة الاستخدام في عبوة كبيرة لا تنتهي منها أعلى منها في عبوة أصغر." },
      { question: "هل يغني المقال عن قراءة ملصق المنتج؟", answer: "تشرح مقالاتنا طرق اختيار المنتجات واستخدامها. أما المكوّنات وتواريخ الصلاحية وتعليمات الحفظ الخاصة بمنتج معين، فارجع بشأنها إلى ملصق العبوة التي تستلمها وصفحة المنتج. وإذا اختلفت التفاصيل، فاستفسر قبل الاستخدام." },
      { question: "ما المعلومات التي أجهّزها قبل الاستفسار عن طلب تجاري؟", answer: "وضّح الاستخدام المقصود والكميات المتوقعة ومساحة التخزين المتاحة وموعد التوصيل المفضّل. تساعد هذه التفاصيل على مناقشة الأسعار والحد الأدنى للكميات وشروط التوصيل مع الفريق." },
    ],
    contact: "تحدث إلى فريق VETRA",
    products: "منتجاتنا",
    home: "الرئيسية",
    blog: "المقالات",
    breadcrumb: "مسار التنقل",
    by: "بقلم",
    contents: "في هذا المقال",
    related: "مقالات ذات صلة",
    relatedIntro: "معرفة إضافية تساعدك في اختيارك المقبل.",
    authorTitle: "اختيار عن معرفة",
    authorBody: "تهتم VETRA بالجودة والتفاصيل والقيمة. ونشارك إرشادات عملية لاختيار المنتجات واستخدامها، لتستند قراراتك إلى معلومات واضحة.",
    imageNote: "صورة توضيحية لموضوع المقال",
    productImageAlt: "عبوة عسل أزهار القهوة من ESHAN",
    productImageNote: "صورة مرجعية للعبوة. تحقّق من التواريخ وتفاصيل التشغيلة على المنتج الذي تستلمه.",
  },
  th: {
    title: "บทความและคู่มือเลือกสินค้า",
    description:
      "คู่มือจาก VETRA เรื่องการเลือกสินค้า อ่านฉลาก เปรียบเทียบคุณภาพและความคุ้มค่า พร้อมรู้จักน้ำผึ้งดอกกาแฟและแนวทางเลือกซื้อสำหรับธุรกิจ",
    eyebrow: "VETRA คัดเลือก",
    heading: "เลือกอย่างเข้าใจ\nได้สิ่งที่คุ้มค่า",
    subtitle: "VETRA เชี่ยวชาญการคัดเลือกสินค้า มาตรฐานสูง ให้ความสำคัญกับคุณภาพ และความคุ้มค่า",
    latest: "บทความทั้งหมด",
    count: "ความรู้ที่ช่วยให้เลือกได้ดีขึ้น",
    read: "อ่านบทความ",
    featured: "เรื่องแนะนำจาก VETRA",
    libraryIntro: "ตั้งแต่รายละเอียดบนฉลาก ไปจนถึงการใช้งานจริง อ่านแนวทางที่ช่วยให้คุณเลือกสินค้าได้ตรงกับความต้องการ",
    all: "ทั้งหมด",
    categories: "เลือกหมวดบทความ",
    search: "ค้นหาบทความ",
    searchPlaceholder: "ลองค้นหา น้ำผึ้ง คุณภาพ หรือขายส่ง",
    clear: "ล้างคำค้นหา",
    results: "พบ {count} บทความ",
    noResults: "ยังไม่พบบทความที่ตรงกับคำค้นหา",
    noResultsBody: "ลองใช้คำสั้นลง หรือเลือกดูบทความทุกหมวด",
    reset: "ดูบทความทั้งหมด",
    minutes: "อ่าน {minutes} นาที",
    approachEyebrow: "มุมมองของ VETRA",
    approachTitle: "สินค้าคุณภาพดี\nคุ้มค่ามากที่สุด",
    approachBody: "การเลือกที่ดีเริ่มจากคำถามที่ตรงจุด เราจึงชวนดูทั้งสิ่งที่อยู่ในสินค้า ความเหมาะสมกับการใช้งาน และคุณค่าที่ได้รับในระยะยาว",
    approachLink: "รู้จักแนวทางของเรา",
    principles: [
      { title: "เข้าใจสินค้า", text: "อ่านส่วนประกอบ แหล่งที่มา และข้อมูลที่ตรวจสอบได้ ก่อนตัดสินจากภาพหรือคำโฆษณา" },
      { title: "เหมาะกับการใช้งาน", text: "เลือกขนาด รูปแบบ และวิธีดูแลให้เข้ากับชีวิตประจำวันหรือความต้องการของธุรกิจ" },
      { title: "มองความคุ้มค่าให้ครบ", text: "พิจารณาคุณภาพ ปริมาณที่ใช้ได้จริง และค่าใช้จ่ายทั้งหมดร่วมกัน" },
    ],
    faqEyebrow: "ก่อนตัดสินใจ",
    faqTitle: "คำถามที่ช่วยให้เลือกง่ายขึ้น",
    questions: [
      { question: "ควรเริ่มเลือกสินค้าจากอะไร?", answer: "เริ่มจากการใช้งานจริงและจำนวนที่ต้องการ แล้วจึงดูส่วนประกอบ ขนาด แหล่งที่มา และวิธีเก็บรักษา วิธีนี้ช่วยให้เปรียบเทียบสินค้าในเงื่อนไขเดียวกันได้ง่ายขึ้น" },
      { question: "สินค้าราคาต่ำที่สุดคุ้มค่าที่สุดเสมอหรือไม่?", answer: "ราคาเป็นส่วนหนึ่งของความคุ้มค่า ควรดูราคาต่อหน่วย ปริมาณที่ใช้ได้จริง และความเหมาะสมด้วย สินค้าขนาดใหญ่ที่ใช้ไม่หมดอาจมีต้นทุนต่อการใช้งานสูงกว่าขนาดเล็ก" },
      { question: "บทความใช้แทนรายละเอียดบนฉลากสินค้าได้หรือไม่?", answer: "บทความช่วยอธิบายแนวทางเลือกซื้อและใช้งาน ส่วนข้อมูลเฉพาะสินค้า เช่น ส่วนประกอบ วันหมดอายุ และวิธีเก็บรักษา ให้ยึดฉลากของสินค้าที่ได้รับและรายละเอียดในหน้าสินค้า หากข้อมูลไม่ตรงกัน ควรสอบถามก่อนใช้" },
      { question: "หากเลือกสินค้าให้ร้านค้าหรือธุรกิจ ควรเตรียมข้อมูลอะไร?", answer: "เตรียมประเภทการใช้งาน จำนวนที่คาดว่าจะใช้ พื้นที่จัดเก็บ และช่วงเวลาที่ต้องการรับสินค้า เพื่อใช้สอบถามราคา จำนวนขั้นต่ำ และเงื่อนไขการจัดส่งกับทีมงาน" },
    ],
    contact: "ปรึกษาทีม VETRA",
    products: "สินค้าของเรา",
    home: "หน้าแรก",
    blog: "บทความ",
    breadcrumb: "เส้นทางของหน้า",
    by: "โดย",
    contents: "เนื้อหาในบทความ",
    related: "อ่านต่อในเรื่องที่เกี่ยวข้อง",
    relatedIntro: "ต่อยอดความเข้าใจ ก่อนเลือกสิ่งที่เหมาะกับคุณ",
    authorTitle: "คัดเลือกด้วยความเข้าใจ",
    authorBody: "VETRA ให้ความสำคัญกับคุณภาพ รายละเอียด และความคุ้มค่า เรารวบรวมแนวทางเลือกซื้อและใช้งาน เพื่อให้คุณตัดสินใจได้จากข้อมูลที่ชัดเจน",
    imageNote: "ภาพประกอบแนวคิดของบทความ",
    productImageAlt: "ภาพบรรจุภัณฑ์น้ำผึ้งดอกกาแฟ ESHAN",
    productImageNote: "ภาพบรรจุภัณฑ์ประกอบข้อมูลสินค้า โปรดตรวจสอบวันที่และเลขล็อตบนสินค้าที่ได้รับ",
  },
  en: {
    title: "Blog & Product Selection Guides",
    description:
      "Practical VETRA guides to choosing products, reading labels, comparing quality and value, enjoying coffee blossom honey, and planning business purchases.",
    eyebrow: "SELECTED BY VETRA",
    heading: "Understand more.\nChoose well.",
    subtitle: "VETRA specialises in selecting products to high standards, with a focus on quality and value.",
    latest: "Explore the articles",
    count: "Knowledge for better choices",
    read: "Read the article",
    featured: "THE VETRA EDIT",
    libraryIntro: "From the details on a label to the way a product fits your day. Find practical guidance for a more considered choice.",
    all: "All articles",
    categories: "Article categories",
    search: "Search articles",
    searchPlaceholder: "Try honey, quality, or wholesale",
    clear: "Clear search",
    results: "{count} articles found",
    noResults: "No articles match your search",
    noResultsBody: "Try a shorter search or explore every category.",
    reset: "Show all articles",
    minutes: "{minutes} min read",
    approachEyebrow: "THE VETRA PERSPECTIVE",
    approachTitle: "Quality products.\nExceptional value.",
    approachBody: "A considered choice starts with the right questions. Look at what is in a product, how it fits your needs, and the value it offers over time.",
    approachLink: "Our approach to selection",
    principles: [
      { title: "Understand the product", text: "Read ingredients, origins, and verifiable details before judging a product by its imagery or advertising." },
      { title: "Choose for real use", text: "Match the size, format, and care requirements to your everyday routine or the needs of your business." },
      { title: "Consider the full value", text: "Compare quality, the amount you will actually use, and the total cost together." },
    ],
    faqEyebrow: "BEFORE YOU CHOOSE",
    faqTitle: "Good questions. Clearer choices.",
    questions: [
      { question: "Where should I start when choosing a product?", answer: "Start with how you will use it and how much you need. Then look at ingredients, size, origin, and storage instructions. This makes it easier to compare products on the same terms." },
      { question: "Is the lowest price always the best value?", answer: "Price is one part of value. Consider the cost per unit, how much you will actually use, and whether the product suits your needs. A large pack that goes unfinished can cost more per use than a smaller one." },
      { question: "Can an article replace the product label?", answer: "Our articles explain approaches to choosing and using products. For specific ingredients, expiry dates, and storage instructions, follow the label on the product you receive and check its product page. Ask before using it if those details differ." },
      { question: "What should I prepare before asking about a business order?", answer: "Share your intended use, expected quantities, available storage, and preferred delivery timing. These details help you discuss pricing, minimum quantities, and delivery terms with the team." },
    ],
    contact: "Talk to VETRA",
    products: "Our products",
    home: "Home",
    blog: "Blog",
    breadcrumb: "Breadcrumb",
    by: "By",
    contents: "In this article",
    related: "Continue exploring",
    relatedIntro: "A little more understanding for your next choice.",
    authorTitle: "Selected with understanding",
    authorBody: "VETRA focuses on quality, thoughtful details, and value. We share practical guidance on choosing and using products, so you can make decisions with clear information.",
    imageNote: "Illustrative imagery for this article",
    productImageAlt: "ESHAN Coffee Blossom Honey packaging",
    productImageNote: "Packaging reference. Check dates and lot details on the item you receive.",
  },
};

export const contactCopy = {
  ar: {
    title: "تواصل معنا",
    description: "اسأل VETRA STORE عن المنتجات والطلبات وشراكات البيع بالجملة.",
    eyebrow: "VETRA STORE",
    heading: "كيف يمكننا مساعدتك؟",
    intro: "استفسر عن منتج أو طلب أو الشراء بالجملة. أخبرنا بما تحتاجه وكيف يمكننا مساعدتك.",
    retail: "المنتجات والطلبات",
    retailBody: "اذكر اسم المنتج والكمية وسؤالك، ليتمكن فريقنا من مراجعة التفاصيل المناسبة.",
    wholesale: "الجملة وقطاع الأعمال",
    wholesaleBody: "للمتاجر والمقاهي والكميات الكبيرة، اختر «الجملة والشراكات»، وأخبرنا بالكمية واحتياجات نشاطك.",
    help: "قبل أن تختار",
    helpBody: "اطّلع على معلومات المنتجات وتفاصيل التوصيل وما ينبغي تأكيده قبل الطلب.",
    helpLink: "المساعدة والمعلومات",
    wholesaleLink: "استفسر عن الجملة",
    newsletterEyebrow: "نسخة تجريبية في المتصفح",
    newsletterTitle: "أخبار VETRA",
  },
  th: {
    title: "ติดต่อเรา",
    description:
      "ส่งคำถามเกี่ยวกับสินค้า การสั่งซื้อ หรือความร่วมมือด้านค้าส่งถึง VETRA STORE",
    eyebrow: "VETRA STORE",
    heading: "ยินดีให้คำปรึกษา",
    intro: "สอบถามสินค้า การสั่งซื้อ หรือขายส่ง บอกสิ่งที่คุณต้องการให้เราช่วยได้ที่นี่",
    retail: "สินค้าและการสั่งซื้อ",
    retailBody:
      "แจ้งชื่อสินค้า จำนวน และคำถามของคุณ เพื่อให้ทีมงานช่วยตรวจสอบรายละเอียดได้ตรงจุด",
    wholesale: "ขายส่งและธุรกิจ",
    wholesaleBody:
      "สำหรับร้านค้า คาเฟ่ และการสั่งซื้อจำนวนมาก เลือกหัวข้อ “ค้าส่งและความร่วมมือ” พร้อมแจ้งจำนวนและลักษณะธุรกิจ",
    help: "ข้อมูลก่อนเลือกซื้อ",
    helpBody: "ดูข้อมูลสินค้า การจัดส่ง และรายละเอียดที่ควรสอบถามก่อนสั่งซื้อ",
    helpLink: "ข้อมูลและความช่วยเหลือ",
    wholesaleLink: "สอบถามขายส่ง",
    newsletterEyebrow: "ตัวอย่างในเบราว์เซอร์",
    newsletterTitle: "ข่าวสารจาก VETRA",
  },
  en: {
    title: "Contact Us",
    description:
      "Ask VETRA STORE about products, ordering, and wholesale partnerships.",
    eyebrow: "VETRA STORE",
    heading: "How can we help?",
    intro: "Ask about a product, an order, or wholesale. Tell us what you need and how we can help.",
    retail: "Products & ordering",
    retailBody:
      "Include the product name, quantity, and your question so our team can check the right details.",
    wholesale: "Wholesale & business",
    wholesaleBody:
      "For shops, cafés, and larger quantities, choose “Wholesale & partnerships” and tell us the quantity and your business needs.",
    help: "Before you choose",
    helpBody: "Find product information, delivery details, and what to confirm before ordering.",
    helpLink: "Help & information",
    wholesaleLink: "Ask about wholesale",
    newsletterEyebrow: "LOCAL DEMO",
    newsletterTitle: "VETRA news",
  },
};

export const helpCopy = {
  ar: {
    title: "المساعدة والمعلومات",
    description: "معلومات المنتجات والطلبات والتوصيل وخدمة العملاء من VETRA STORE للأفراد وقطاع الأعمال.",
    eyebrow: "تفاصيل تهمك",
    heading: "معلومات واضحة لاختيار أسهل",
    intro: "ما تحتاج إلى معرفته قبل الطلب، وإجابات عن استخدام الموقع.",
    faq: "أسئلة عن المنتجات",
    shipping: "الطلب والتوصيل",
    returns: "مشكلات المنتج",
    privacy: "معلومات الخصوصية",
    wholesale: "الجملة وقطاع الأعمال",
    wholesaleLink: "استفسر عن الجملة",
    productLink: "تصفّح جميع المنتجات",
    demoTitle: "جرّب الموقع",
    demoLink: "إدارة السجلات التجريبية",
    demoText: "في الوضع التجريبي، تُحفظ الرسائل وطلبات الشراء في هذا المتصفح فقط. لا تُرسل رسائل بريد إلكتروني ولا تُجرى عمليات دفع أو توصيل. ويمكن مسح السجلات التجريبية من صفحة الإدارة.",
    questions: [
      ["ما المنتجات التي يمكنني الاطّلاع عليها حاليًا؟", "تصفّح صفحة المنتجات للاطّلاع على المنتجات والعلامات التجارية المعروضة حاليًا وتفاصيل كل منتج."],
      ["أين أجد معلومات مكوّنات المنتج ومواده ومنشئه؟", "راجع تفاصيل كل منتج وملصقه أو عبوته لمعرفة المكوّنات أو المواد والمنشأ المذكور. تختلف هذه المعلومات بحسب المنتج؛ تواصل مع فريقنا إذا لم تتضح معلومة أو لم تجدها."],
      ["أين أجد تعليمات الحفظ والعناية بالمنتج؟", "راجع تعليمات الحفظ والعناية في تفاصيل كل منتج وعلى ملصقه أو عبوته. اتبع التعليمات الموجودة على المنتج الذي تستلمه، وتواصل معنا إذا لم تتضح معلومة."],
      ["أين أجد أسعار المنتجات؟", "راجع صفحة كل منتج للاطّلاع على السعر المعروض والكمية والعملة. إذا كان السعر مرجعيًا، فتحقّق من شروط الدفع والعملة التي ستُحصّل بها الدفعة قبل الدفع. تواصل معنا للاستفسار عن كميات الجملة أو الحصول على عرض سعر للتوصيل."],
      ["هل تُعدّ إضافة المنتج إلى السلة طلب شراء؟", "لا. يجب أن يؤكد فريقنا توافر المنتج ورسوم التوصيل وتفاصيل الدفع قبل متابعة الطلب. وفي الوضع التجريبي، تبقى الطلبات في هذا المتصفح فقط."],
    ],
    shippingText: storeDetails.ar.shipping.description,
    shippingNote: storeDetails.ar.stock.description,
    returnsText: storeDetails.ar.returns.description,
    privacyText: "يستخدم نموذج التواصل اسمك وعنوان بريدك الإلكتروني والموضوع والرسالة للرد على استفسارك. عند تفعيل الخدمات الفعلية، تُحفظ البيانات المرسلة بعد تأكيد النظام نجاح العملية فقط.",
    privacyText2: "في الوضع التجريبي، تبقى البيانات في متصفحك لاختبار الخطوات، ولا تُرسل إلى فريقنا. استخدم بيانات افتراضية، ولا تدخل بيانات بطاقات الدفع أو كلمات المرور أو المعلومات الحساسة. وعند استخدام الخدمات الفعلية، اختر «المعلومات الشخصية» في صفحة التواصل للاستفسار عن الخصوصية.",
    contact: "تواصل معنا",
    note: "لديك سؤال آخر؟ أخبرنا بمزيد من التفاصيل.",
  },
  th: {
    title: "ข้อมูลและความช่วยเหลือ",
    description: "ข้อมูลสินค้า การสั่งซื้อ การจัดส่ง และการดูแลจาก VETRA STORE สำหรับปลีกและธุรกิจ",
    eyebrow: "รายละเอียดที่ควรรู้",
    heading: "ข้อมูลที่ช่วยให้เลือกง่ายขึ้น",
    intro: "รายละเอียดสำคัญก่อนสั่งซื้อ และคำตอบสำหรับการใช้งานเว็บไซต์",
    faq: "คำถามเกี่ยวกับสินค้า",
    shipping: "การสั่งซื้อและจัดส่ง",
    returns: "ปัญหาเกี่ยวกับสินค้า",
    privacy: "ข้อมูลความเป็นส่วนตัว",
    wholesale: "ขายส่งและธุรกิจ",
    wholesaleLink: "สอบถามขายส่ง",
    productLink: "ดูสินค้าทั้งหมด",
    demoTitle: "ทดลองใช้งานเว็บไซต์",
    demoLink: "จัดการข้อมูลทดลอง",
    demoText: "ในโหมดทดลอง ข้อความและรายการสั่งซื้อบันทึกไว้ในเบราว์เซอร์นี้เท่านั้น ไม่มีการส่งอีเมล รับชำระเงิน หรือจัดส่งสินค้า ข้อมูลทดลองสามารถล้างได้จากหน้าจัดการ",
    questions: [
      [
        "ขณะนี้มีสินค้าอะไรบ้าง?",
        "ดูรายการสินค้าและแบรนด์ที่แสดงอยู่ในหน้าสินค้า พร้อมรายละเอียดของสินค้าแต่ละรายการ",
      ],
      [
        "ดูส่วนประกอบ วัสดุ และแหล่งที่มาของสินค้าได้ที่ไหน?",
        "อ่านรายละเอียดสินค้าแต่ละรายการและฉลากหรือบรรจุภัณฑ์ เพื่อดูส่วนประกอบหรือวัสดุและแหล่งที่มาที่ระบุ ข้อมูลเหล่านี้แตกต่างกันตามสินค้า ติดต่อทีมงานหากข้อมูลไม่ชัดเจนหรือไม่พบรายละเอียดที่ต้องการ",
      ],
      [
        "ดูคำแนะนำการเก็บรักษาและดูแลสินค้าได้ที่ไหน?",
        "อ่านคำแนะนำการเก็บรักษาและดูแลในรายละเอียดสินค้าแต่ละรายการ รวมถึงฉลากหรือบรรจุภัณฑ์ ปฏิบัติตามคำแนะนำบนสินค้าที่ได้รับ และติดต่อเราหากมีข้อมูลที่ไม่ชัดเจน",
      ],
      [
        "ดูราคาสินค้าได้ที่ไหน?",
        "ดูราคา จำนวน และสกุลเงินที่แสดงในหน้าสินค้าแต่ละรายการ หากเป็นราคาอ้างอิง ให้ตรวจสอบเงื่อนไขการชำระและสกุลเงินที่เรียกเก็บก่อนชำระ สอบถามทีมงานเรื่องจำนวนขายส่งหรือค่าจัดส่งได้",
      ],
      [
        "เพิ่มสินค้าในตะกร้าแล้วถือว่าสั่งซื้อหรือยัง?",
        "ยังไม่ถือเป็นการสั่งซื้อหรือชำระเงินที่ยืนยันแล้ว ทีมงานต้องยืนยันสินค้า ค่าจัดส่ง และการชำระเงินก่อนดำเนินการ ในโหมดทดลอง รายการจะอยู่ในเบราว์เซอร์นี้เท่านั้น",
      ],
    ],
    shippingText:
      storeDetails.th.shipping.description,
    shippingNote:
      storeDetails.th.stock.description,
    returnsText: storeDetails.th.returns.description,
    privacyText:
      "แบบฟอร์มติดต่อใช้ชื่อ อีเมล หัวข้อ และข้อความเพื่อประกอบการตอบคำถาม เมื่อเปิดใช้บริการจริง ข้อมูลที่ส่งจะบันทึกหลังจากระบบยืนยันสำเร็จเท่านั้น",
    privacyText2:
      "ในโหมดทดลอง ข้อมูลจะเก็บในเบราว์เซอร์ของคุณเพื่อทดสอบขั้นตอน ไม่ส่งถึงทีมงาน กรุณาใช้ข้อมูลสมมติ และอย่าใส่ข้อมูลบัตรชำระเงิน รหัสผ่าน หรือข้อมูลอ่อนไหว หากใช้บริการจริงและต้องการสอบถามข้อมูลส่วนบุคคล ให้เลือกหัวข้อ “ข้อมูลส่วนบุคคล” ในหน้าติดต่อเรา",
    contact: "ติดต่อเรา",
    note: "ยังมีคำถามเพิ่มเติม? เราพร้อมรับฟังรายละเอียดจากคุณ",
  },
  en: {
    title: "Help & Information",
    description: "Product, ordering, delivery, and customer care information from VETRA STORE for individuals and businesses.",
    eyebrow: "THE DETAILS THAT MATTER",
    heading: "Clear details. Easier choices.",
    intro: "What to know before ordering, and answers about using the website.",
    faq: "Product questions",
    shipping: "Ordering & delivery",
    returns: "Product concerns",
    privacy: "Privacy information",
    wholesale: "Wholesale & business",
    wholesaleLink: "Ask about wholesale",
    productLink: "Browse all products",
    demoTitle: "Try the website",
    demoLink: "Manage demo records",
    demoText: "In demo mode, messages and order requests are saved in this browser only. No email, payment, or delivery takes place. Demo records can be cleared from the management page.",
    questions: [
      [
        "Which products are available to explore?",
        "Browse the catalog for the products and brands currently shown, with details for each product.",
      ],
      [
        "Where can I find a product's ingredients, materials and origin?",
        "Check each product's details and its label or packaging for the listed ingredients or materials and origin. These details vary by product; ask our team if anything is unclear or missing.",
      ],
      [
        "Where can I find storage and care instructions?",
        "Read the storage and care instructions in each product's details and on its label or packaging. Follow the instructions on the product you receive, and contact us if anything is unclear.",
      ],
      [
        "Where can I find product prices?",
        "Check each product page for the displayed price, quantity and currency. If a reference price is shown, check the charging currency and payment terms before paying. Ask our team about wholesale quantities or a delivery quote.",
      ],
      [
        "Does adding to the cart place an order?",
        "No. Our team must confirm availability, delivery charges, and payment before an order proceeds. In demo mode, requests stay in this browser only.",
      ],
    ],
    shippingText:
      storeDetails.en.shipping.description,
    shippingNote:
      storeDetails.en.stock.description,
    returnsText: storeDetails.en.returns.description,
    privacyText:
      "The contact form uses your name, email address, subject, and message to support a reply. When live services are enabled, submitted details are saved only after the system confirms success.",
    privacyText2:
      "In demo mode, data is kept in your browser to test the workflow and is not sent to our team. Use sample details, and do not enter payment card details, passwords, or sensitive information. When using live services, choose Personal information on our contact page for privacy questions.",
    contact: "Contact us",
    note: "Still have a question? Share a little more with us.",
  },
};

export const pageCopySources = { story: storyCopy, journal: journalCopy, contact: contactCopy, help: helpCopy, ui: editorialUi };
