import type { Localized } from "@/lib/i18n";

const en = {
  methodTitle: "How would you like to continue?",
  enquiry: "Send an enquiry",
  enquiryDescription: "Ask our team to confirm availability and delivery. No payment is taken.",
  online: "Pay securely online",
  onlineDescription: "Pay in Thai baht on your chosen provider's secure checkout page. Free delivery within Thailand.",
  providerLabel: "Payment provider",
  providerFailure: "This provider could not start payment. Choose another available provider, or try again. We have not changed your selection.",
  previousOrder: "This payment window expired or your details differ from the original order. Start a new checkout to continue.",
  newCheckout: "Start a new checkout",
  postcodeHint: "Enter a 5-digit Thai delivery postcode to enable online payment.",
  amountLabel: "Amount to pay in Thai baht",
  amountNote: "This includes free delivery in Thailand. We verify the amount again before opening secure checkout.",
  paymentConsent: "I agree to share these details so VETRA STORE can process my order and payment, as described in",
  pay: "Continue to secure payment",
  starting: "Opening secure payment…",
  startError: "We could not open secure payment. Your details are still here. Please check for an existing payment before trying again.",
  priceChanged: "The price changed. Please review your bag before trying again. No payment was taken.",
  resultTitle: "Payment status",
  loading: "Checking the payment with VETRA STORE…",
  pendingTitle: "Waiting for payment confirmation",
  pendingBody: "Your payment is being checked. This page refreshes for about a minute; you can check again later. If you left the payment page without paying, return to checkout to continue.",
  paidTitle: "Payment confirmed",
  paidBody: "Your payment has been verified. Keep your reference for any questions about the order.",
  failedTitle: "Payment was not completed",
  failedBody: "No successful payment has been confirmed for this attempt. Your bag is still available if you would like to try again.",
  missingTitle: "Payment reference unavailable",
  missingBody: "We could not identify an order to check. Return to checkout or contact our team if you already attempted payment.",
  statusErrorTitle: "Status temporarily unavailable",
  statusErrorBody: "We could not confirm the current payment status. Keep this page link and check again before starting another payment.",
  reference: "Order reference",
  refresh: "Check again",
  returnCheckout: "Return to checkout",
  browse: "View products",
  contact: "Contact our team",
};

export const paymentCheckoutCopy: Localized<typeof en> = {
  en,
  ar: {
    methodTitle: "كيف تود متابعة الطلب؟",
    enquiry: "إرسال استفسار",
    enquiryDescription: "دع فريقنا يؤكد توفر المنتجات والتوصيل. لن تُحصّل أي دفعة.",
    online: "الدفع الآمن عبر الإنترنت",
    onlineDescription: "ادفع بالبات التايلاندي عبر صفحة الدفع الآمنة لدى المزوّد الذي تختاره. التوصيل مجاني داخل تايلاند.",
    providerLabel: "مزوّد الدفع",
    providerFailure: "تعذّر بدء الدفع عبر هذا المزوّد. اختر مزوّدًا آخر متاحًا، أو أعد المحاولة. لم نغيّر اختيارك تلقائيًا.",
    previousOrder: "انتهت مهلة الدفع لهذا الطلب أو اختلفت بياناتك عن الطلب الأصلي. ابدأ إتمام طلب جديد للمتابعة.",
    newCheckout: "بدء إتمام طلب جديد",
    postcodeHint: "أدخل الرمز البريدي التايلاندي لعنوان التوصيل، المكوّن من 5 أرقام، لتفعيل الدفع عبر الإنترنت.",
    amountLabel: "المبلغ المطلوب بالبات التايلاندي",
    amountNote: "يشمل التوصيل المجاني داخل تايلاند. نتحقق من المبلغ مجددًا قبل فتح صفحة الدفع الآمنة.",
    paymentConsent: "أوافق على استخدام هذه البيانات لمعالجة طلبي ودفعة الشراء، وفقًا لما ورد في",
    pay: "المتابعة إلى الدفع الآمن",
    starting: "جارٍ فتح صفحة الدفع الآمنة…",
    startError: "تعذّر فتح صفحة الدفع الآمنة. بياناتك ما زالت هنا. يُرجى التحقق من عدم وجود دفعة سابقة قبل المحاولة مجددًا.",
    priceChanged: "تغيّر السعر. يُرجى مراجعة سلتك قبل المحاولة مجددًا. لم تُحصّل أي دفعة.",
    resultTitle: "حالة الدفع",
    loading: "جارٍ التحقق من الدفع لدى VETRA STORE…",
    pendingTitle: "بانتظار تأكيد الدفع",
    pendingBody: "يجري التحقق من دفعتك. ستُحدَّث الصفحة لمدة دقيقة تقريبًا، ويمكنك إعادة التحقق لاحقًا. إذا غادرت صفحة الدفع دون السداد، فعد إلى إتمام الطلب للمتابعة.",
    paidTitle: "تأكد استلام الدفعة",
    paidBody: "تم التحقق من دفعتك. احتفظ برقم المرجع لأي استفسار بشأن الطلب.",
    failedTitle: "لم تكتمل عملية الدفع",
    failedBody: "لم نتلقَّ تأكيدًا بنجاح الدفع لهذه المحاولة. لا تزال سلتك متاحة إذا أردت المحاولة مجددًا.",
    missingTitle: "رقم مرجع الدفع غير متاح",
    missingBody: "تعذّر تحديد الطلب للتحقق منه. عُد إلى صفحة الطلب أو تواصل مع فريقنا إذا حاولت الدفع بالفعل.",
    statusErrorTitle: "حالة الدفع غير متاحة مؤقتًا",
    statusErrorBody: "تعذّر تأكيد حالة الدفع الآن. احتفظ برابط هذه الصفحة وأعد التحقق قبل بدء محاولة دفع أخرى.",
    reference: "رقم مرجع الطلب",
    refresh: "إعادة التحقق",
    returnCheckout: "العودة إلى إتمام الطلب",
    browse: "عرض المنتجات",
    contact: "التواصل مع فريقنا",
  },
  th: {
    methodTitle: "เลือกวิธีดำเนินการต่อ",
    enquiry: "ส่งคำสอบถาม",
    enquiryDescription: "ให้ทีมงานยืนยันสินค้าและการจัดส่ง โดยยังไม่มีการชำระเงิน",
    online: "ชำระเงินออนไลน์อย่างปลอดภัย",
    onlineDescription: "ชำระเป็นเงินบาทผ่านหน้าชำระเงินที่ปลอดภัยของผู้ให้บริการที่คุณเลือก พร้อมจัดส่งฟรีในประเทศไทย",
    providerLabel: "ผู้ให้บริการชำระเงิน",
    providerFailure: "ผู้ให้บริการนี้ยังเริ่มการชำระเงินไม่ได้ กรุณาเลือกผู้ให้บริการอื่นที่พร้อมใช้งานหรือลองอีกครั้ง ระบบจะไม่เปลี่ยนผู้ให้บริการแทนคุณ",
    previousOrder: "ระยะเวลาชำระเงินของคำสั่งซื้อนี้หมดแล้ว หรือข้อมูลของคุณต่างจากรายการเดิม กรุณาเริ่มขั้นตอนชำระเงินใหม่",
    newCheckout: "เริ่มชำระเงินรายการใหม่",
    postcodeHint: "กรอกรหัสไปรษณีย์ของที่อยู่จัดส่งในไทย 5 หลัก เพื่อเปิดใช้การชำระเงินออนไลน์",
    amountLabel: "ยอดชำระเป็นเงินบาท",
    amountNote: "รวมจัดส่งฟรีในประเทศไทย ระบบจะตรวจสอบยอดอีกครั้งก่อนเปิดหน้าชำระเงินที่ปลอดภัย",
    paymentConsent: "ฉันยินยอมให้ VETRA STORE ใช้ข้อมูลเหล่านี้เพื่อดำเนินการคำสั่งซื้อและการชำระเงิน ตามที่ระบุใน",
    pay: "ไปยังหน้าชำระเงินที่ปลอดภัย",
    starting: "กำลังเปิดหน้าชำระเงิน…",
    startError: "ยังเปิดหน้าชำระเงินไม่ได้ ข้อมูลของคุณยังอยู่ กรุณาตรวจสอบว่ามีการชำระเงินก่อนหน้านี้หรือไม่ ก่อนลองอีกครั้ง",
    priceChanged: "ราคามีการเปลี่ยนแปลง กรุณาตรวจสอบตะกร้าก่อนลองอีกครั้ง ยังไม่มีการเรียกเก็บเงิน",
    resultTitle: "สถานะการชำระเงิน",
    loading: "กำลังตรวจสอบการชำระเงินกับ VETRA STORE…",
    pendingTitle: "รอยืนยันการชำระเงิน",
    pendingBody: "ระบบกำลังตรวจสอบการชำระเงิน หน้านี้จะอัปเดตประมาณหนึ่งนาที และคุณสามารถตรวจสอบอีกครั้งภายหลัง หากออกจากหน้าชำระเงินโดยยังไม่ได้จ่าย ให้กลับไปหน้าชำระเงินเพื่อดำเนินการต่อ",
    paidTitle: "ยืนยันการชำระเงินแล้ว",
    paidBody: "ตรวจสอบการชำระเงินเรียบร้อยแล้ว กรุณาเก็บหมายเลขอ้างอิงไว้หากต้องการสอบถามเกี่ยวกับคำสั่งซื้อ",
    failedTitle: "การชำระเงินยังไม่สำเร็จ",
    failedBody: "ยังไม่มีการยืนยันว่าชำระเงินสำเร็จสำหรับครั้งนี้ ตะกร้าของคุณยังอยู่หากต้องการลองอีกครั้ง",
    missingTitle: "ไม่พบหมายเลขอ้างอิงการชำระเงิน",
    missingBody: "เราไม่สามารถระบุคำสั่งซื้อที่จะตรวจสอบได้ กรุณากลับไปหน้าชำระเงินหรือติดต่อทีมงานหากคุณได้ลองชำระแล้ว",
    statusErrorTitle: "ตรวจสอบสถานะไม่ได้ชั่วคราว",
    statusErrorBody: "ยังยืนยันสถานะการชำระเงินไม่ได้ กรุณาเก็บลิงก์หน้านี้ไว้และตรวจสอบอีกครั้งก่อนเริ่มชำระเงินใหม่",
    reference: "หมายเลขอ้างอิงคำสั่งซื้อ",
    refresh: "ตรวจสอบอีกครั้ง",
    returnCheckout: "กลับไปหน้าชำระเงิน",
    browse: "ดูสินค้า",
    contact: "ติดต่อทีมงาน",
  },
};

const publicEn = {
  deliveryNote: "Online payment in THB is currently available through Thai checkout for delivery in Thailand. For other destinations, send an enquiry. Adding to your bag does not place an order.",
  summaryNote: "Prices shown in USD are for reference. Online payment is charged in THB through Thai checkout for delivery in Thailand.",
  honeyFaq: "Add honey to your bag to review your selection. For delivery in Thailand, use Thai checkout with a 5-digit Thai postcode to pay in THB. For other destinations or wholesale, contact our team. Adding to the bag alone does not place an order.",
};

export const publicPaymentCopy: Localized<typeof publicEn> = {
  en: publicEn,
  ar: {
    deliveryNote: "الدفع عبر الإنترنت بالبات التايلاندي متاح حاليًا عبر صفحة إتمام الطلب باللغة التايلاندية للتوصيل داخل تايلاند. للوجهات الأخرى، أرسل استفسارًا. إضافة المنتجات إلى السلة لا تُعدّ طلب شراء.",
    summaryNote: "الأسعار بالدولار الأمريكي للعرض فقط. تُحصّل المدفوعات عبر الإنترنت بالبات التايلاندي عند إتمام الطلب باللغة التايلاندية للتوصيل داخل تايلاند.",
    honeyFaq: "أضف العسل إلى سلتك لمراجعة اختياراتك. للتوصيل داخل تايلاند، استخدم صفحة إتمام الطلب باللغة التايلاندية مع رمز بريدي تايلاندي من 5 أرقام للدفع بالبات. للوجهات الأخرى أو البيع بالجملة، تواصل مع فريقنا. إضافة المنتج إلى السلة وحدها لا تُنشئ طلبًا.",
  },
  th: {
    deliveryNote: "จัดส่งฟรีในประเทศไทย กรอกรหัสไปรษณีย์ไทย 5 หลักในขั้นตอนชำระเงินเพื่อชำระเป็นเงินบาท การเพิ่มสินค้าในตะกร้ายังไม่ถือเป็นการสั่งซื้อ",
    summaryNote: "จัดส่งฟรีในประเทศไทย ระบบจะตรวจสอบยอดเงินบาทอีกครั้งก่อนเปิดหน้าชำระเงิน",
    honeyFaq: "เพิ่มน้ำผึ้งลงตะกร้าและตรวจสอบรายการ จากนั้นกรอกรหัสไปรษณีย์ไทย 5 หลักเพื่อชำระเป็นเงินบาทพร้อมจัดส่งฟรีในประเทศไทย หากต้องการซื้อส่งหรือจัดส่งไปต่างประเทศ กรุณาติดต่อทีมงาน การเพิ่มลงตะกร้ายังไม่ถือเป็นการสั่งซื้อ",
  },
};
