import type { Localized } from "@/lib/i18n";
const en = {
  shared: "Shared inbox", browser: "Browser demo", intro: "Private requests saved on the server. Order progress and delivery controls are simulations; no money, parcels or emails are sent.", sourceNote: "Browser demo data stays separate. Sync imports saved website enquiries without changing their original details or prices.", refresh: "Sync and refresh", load: "Loading shared requests…", empty: "No matching shared requests. Sync saved enquiries or create a test enquiry.", add: "Create test enquiry", archived: "Archived requests", active: "Active requests", archive: "Archive", restore: "Restore", close: "Close", save: "Save changes", saved: "Saved on the server", failed: "Could not confirm this action. Your input is preserved. Retry the same action or refresh to review the latest record.", conflict: "This record changed. Your draft is preserved. Close and reopen the record to review the latest version before saving again.", unauthorized: "Your session has expired or this action needs an owner account. Sign in again; your draft is still here.", stockError: "Not enough stock remains for this simulation. No order changes were saved.", filters: "Filter requests", search: "Name, email, reference, business or assignee", emailHistory: "View this customer’s requests", clearEmail: "Clear customer filter", source: "Source", sourceLabels: { "staff-test": "Staff test", "website-test": "Website test enquiry", contact: "Website enquiry", order: "Website order enquiry" }, page: "Page", previous: "Previous page", next: "Next page", revision: "Revision", notes: "Staff notes", simulation: "Simulation only", states: { ready: "Ready for simulation", processing: "Saved attempt needs resolution", "mock-delivered": "Simulated delivery confirmed", failed: "Simulated delivery failed", exhausted: "Retry limit reached" }, resolve: "Resolve saved attempt", deliver: "Run simulated delivery", receipt: "Simulated receipt", attempts: "Attempts", ownerOnly: "An owner account is required for simulation controls.", testNote: "Fictional test enquiry saved in the shared inbox. It will never send an email or charge a customer.", name: "Name", email: "Email", message: "Message", postcode: "Postcode (optional)", kind: "Request type", quantity: "Quantity", product: "Product", submit: "Save test enquiry", pendingImports: "More saved enquiries remain. Sync again to import the next batch.", noSource: "The source database is not configured. Shared test requests still work in local CMS storage.", synced: "Saved enquiries synchronized", stock: "Stock allocation", stockStates: { none: "Not reserved", reserved: "Reserved", committed: "Committed", released: "Released" }, expires: "Reservation expires", customerContext: "Customer context", archiveNote: "Archiving removes a request from the active inbox and keeps its history and stock allocation. It can be restored.", settings: "Shared simulation settings", activity: "Activity", loadingDetail: "Loading request…",
};
export const sharedOperationsCopy: Localized<typeof en> = { en, ar: {
  "shared": "صندوق الاستفسارات المشترك",
  "browser": "تجربة المتصفح",
  "intro": "استفسارات خاصة محفوظة على الخادم. خطوات الطلب وأدوات التسليم محاكاة؛ لا تُرسل أموال أو طرود أو رسائل بريد إلكتروني.",
  "sourceNote": "تظل بيانات تجربة المتصفح منفصلة. تستورد المزامنة استفسارات الموقع المحفوظة دون تغيير تفاصيلها أو أسعارها الأصلية.",
  "refresh": "مزامنة وتحديث",
  "load": "جارٍ تحميل الاستفسارات المشتركة…",
  "empty": "لا توجد استفسارات مشتركة مطابقة. زامن الاستفسارات المحفوظة أو أنشئ استفسارًا تجريبيًا.",
  "add": "إنشاء استفسار تجريبي",
  "archived": "الاستفسارات المؤرشفة",
  "active": "الاستفسارات النشطة",
  "archive": "أرشفة",
  "restore": "استعادة",
  "close": "إغلاق",
  "save": "حفظ التغييرات",
  "saved": "تم الحفظ على الخادم",
  "failed": "تعذّر تأكيد هذا الإجراء. ما زالت بياناتك محفوظة. أعد الإجراء نفسه أو حدّث الصفحة لمراجعة أحدث سجل.",
  "conflict": "تغيّر هذا السجل. ما زالت مسودتك محفوظة. أغلق السجل وافتحه مجددًا لمراجعة أحدث إصدار قبل الحفظ.",
  "unauthorized": "انتهت جلستك أو يتطلب هذا الإجراء حساب مالك المتجر. سجّل الدخول مجددًا؛ ما زالت مسودتك موجودة.",
  "stockError": "المخزون المتبقي لا يكفي لهذه المحاكاة. لم تُحفظ تغييرات الطلب.",
  "filters": "تصفية الاستفسارات",
  "search": "الاسم أو البريد الإلكتروني أو المرجع أو النشاط التجاري أو المسؤول",
  "emailHistory": "عرض استفسارات هذا العميل",
  "clearEmail": "إلغاء تصفية العميل",
  "source": "المصدر",
  "sourceLabels": {
    "staff-test": "اختبار الفريق",
    "website-test": "استفسار تجريبي من الموقع",
    "contact": "استفسار من الموقع",
    "order": "استفسار طلب من الموقع"
  },
  "page": "صفحة",
  "previous": "الصفحة السابقة",
  "next": "الصفحة التالية",
  "revision": "الإصدار",
  "notes": "ملاحظات الفريق",
  "simulation": "محاكاة فقط",
  "states": {
    "ready": "جاهز للمحاكاة",
    "processing": "المحاولة المحفوظة بحاجة إلى التحقق",
    "mock-delivered": "تم تأكيد التسليم التجريبي",
    "failed": "تعذّر التسليم التجريبي",
    "exhausted": "تم بلوغ حد المحاولات"
  },
  "resolve": "التحقق من المحاولة المحفوظة",
  "deliver": "تشغيل محاكاة التسليم",
  "receipt": "إيصال تجريبي",
  "attempts": "المحاولات",
  "ownerOnly": "يلزم حساب مالك المتجر لاستخدام أدوات المحاكاة.",
  "testNote": "استفسار تجريبي افتراضي يُحفظ في الصندوق المشترك. لن يرسل بريدًا إلكترونيًا ولن يخصم أي مبلغ من العميل.",
  "name": "الاسم",
  "email": "البريد الإلكتروني",
  "message": "الرسالة",
  "postcode": "الرمز البريدي (اختياري)",
  "kind": "نوع الاستفسار",
  "quantity": "الكمية",
  "product": "المنتج",
  "submit": "حفظ الاستفسار التجريبي",
  "pendingImports": "توجد استفسارات محفوظة أخرى. زامن مجددًا لاستيراد الدفعة التالية.",
  "noSource": "لم تُضبط قاعدة بيانات المصدر. تظل الاستفسارات التجريبية المشتركة متاحة في تخزين الإدارة المحلي.",
  "synced": "تمت مزامنة الاستفسارات المحفوظة",
  "stock": "تخصيص المخزون",
  "stockStates": {
    "none": "غير محجوز",
    "reserved": "محجوز",
    "committed": "خُصم من المخزون",
    "released": "أُعيد إلى المخزون"
  },
  "expires": "انتهاء الحجز",
  "customerContext": "معلومات العميل",
  "archiveNote": "تزيل الأرشفة الاستفسار من الصندوق النشط مع الاحتفاظ بسجله وتخصيص مخزونه. يمكن استعادته لاحقًا.",
  "settings": "إعدادات المحاكاة المشتركة",
  "activity": "سجل النشاط",
  "loadingDetail": "جارٍ تحميل الاستفسار…"
}, th: {
  shared: "คำขอบนเซิร์ฟเวอร์", browser: "ตัวอย่างในเบราว์เซอร์", intro: "คำขอส่วนตัวที่บันทึกบนเซิร์ฟเวอร์ ขั้นตอนสั่งซื้อและการแจ้งเตือนเป็นการจำลอง ไม่มีการเรียกเก็บเงิน ส่งพัสดุ หรือส่งอีเมล", sourceNote: "ข้อมูลตัวอย่างในเบราว์เซอร์แยกต่างหาก การซิงก์นำคำสอบถามที่บันทึกแล้วเข้ามา โดยไม่เปลี่ยนรายละเอียดและราคาเดิม", refresh: "ซิงก์และโหลดใหม่", load: "กำลังโหลดคำขอ…", empty: "ไม่พบคำขอที่ตรงกัน ซิงก์คำสอบถามที่บันทึกไว้ หรือสร้างคำขอทดสอบ", add: "สร้างคำขอทดสอบ", archived: "รายการที่เก็บถาวร", active: "รายการปัจจุบัน", archive: "เก็บถาวร", restore: "นำกลับ", close: "ปิด", save: "บันทึกการแก้ไข", saved: "บันทึกบนเซิร์ฟเวอร์แล้ว", failed: "ยังยืนยันการทำรายการไม่ได้ ข้อมูลที่กรอกยังอยู่ ลองทำรายการเดิมอีกครั้ง หรือโหลดข้อมูลล่าสุดเพื่อตรวจสอบ", conflict: "รายการนี้มีการเปลี่ยนแปลงแล้ว ข้อมูลที่กรอกยังอยู่ กรุณาปิดและเปิดรายการใหม่เพื่อตรวจสอบก่อนบันทึกอีกครั้ง", unauthorized: "เซสชันหมดอายุ หรือรายการนี้ต้องใช้บัญชีเจ้าของร้าน กรุณาเข้าสู่ระบบใหม่ ข้อมูลที่กรอกยังอยู่", stockError: "สต็อกสำหรับการจำลองไม่เพียงพอ ยังไม่บันทึกการเปลี่ยนแปลงคำสั่งซื้อ", filters: "กรองคำขอ", search: "ชื่อ อีเมล เลขอ้างอิง ธุรกิจ หรือผู้รับผิดชอบ", emailHistory: "ดูคำขอของลูกค้ารายนี้", clearEmail: "ล้างตัวกรองลูกค้า", source: "ที่มา", sourceLabels: { "staff-test": "ทีมงานทดสอบ", "website-test": "คำสอบถามทดสอบจากเว็บไซต์", contact: "คำสอบถามจากเว็บไซต์", order: "คำสอบถามสั่งซื้อจากเว็บไซต์" }, page: "หน้า", previous: "หน้าก่อน", next: "หน้าถัดไป", revision: "ฉบับ", notes: "บันทึกทีมงาน", simulation: "การจำลองเท่านั้น", states: { ready: "พร้อมทดสอบ", processing: "ต้องตรวจสอบผลรายการที่บันทึกไว้", "mock-delivered": "ยืนยันการส่งจำลองแล้ว", failed: "ส่งจำลองไม่สำเร็จ", exhausted: "ครบจำนวนครั้งที่ลองใหม่" }, resolve: "ตรวจสอบผลรายการที่บันทึกไว้", deliver: "ทดลองส่งการแจ้งเตือน", receipt: "เลขยืนยันจำลอง", attempts: "จำนวนครั้ง", ownerOnly: "ต้องใช้บัญชีเจ้าของร้านเพื่อใช้ตัวควบคุมจำลอง", testNote: "คำสอบถามสมมติที่บันทึกในกล่องคำขอบนเซิร์ฟเวอร์ ไม่ส่งอีเมลหรือเรียกเก็บเงินจากลูกค้า", name: "ชื่อ", email: "อีเมล", message: "ข้อความ", postcode: "รหัสไปรษณีย์ (ไม่บังคับ)", kind: "ประเภทคำขอ", quantity: "จำนวน", product: "สินค้า", submit: "บันทึกคำขอทดสอบ", pendingImports: "ยังมีคำสอบถามเหลืออยู่ กดซิงก์อีกครั้งเพื่อนำเข้าชุดถัดไป", noSource: "ยังไม่ตั้งค่าฐานข้อมูลต้นทาง สามารถบันทึกคำขอทดสอบในพื้นที่ CMS ภายในเครื่องได้", synced: "ซิงก์คำสอบถามที่บันทึกไว้แล้ว", stock: "การจองสต็อก", stockStates: { none: "ยังไม่จอง", reserved: "จองแล้ว", committed: "ตัดสต็อกแล้ว", released: "คืนสต็อกแล้ว" }, expires: "การจองหมดอายุ", customerContext: "ข้อมูลลูกค้า", archiveNote: "การเก็บถาวรซ่อนคำขอจากกล่องปัจจุบัน โดยเก็บประวัติและการจองสต็อกไว้ และสามารถนำกลับได้", settings: "การตั้งค่าจำลองบนเซิร์ฟเวอร์", activity: "ประวัติ", loadingDetail: "กำลังโหลดรายการ…",
} };
