import { workflowArabic } from "@/content/customer-ar";
import type { Localized } from "@/lib/i18n";
const en = {
  wholesaleLink: "Enquire for your business", requestsTitle: "Requests saved in this browser", requestsNote: "Local preview history on this browser only. Tracking and payment progress are simulated.", noRequests: "Your saved order previews will appear here.", cancelRequest: "Cancel this simulated request",
  wholesaleTitle: "Tell us what your business needs", product: "Product", chooseProduct: "Select a product", quantity: "Estimated quantity (units)", business: "Business name / business type", destination: "Delivery province, postcode or destination", neededBy: "Preferred delivery date (optional)", phone: "Phone (optional)", wholesaleNote: "This is an enquiry. Availability, minimum quantities, prices and delivery dates need confirmation from our team.",
  assignedTo: "Assigned to", unassigned: "Unassigned", saveAssignment: "Save assignment", saved: "Saved", failed: "Could not save. Check the details and try again; your input is preserved.", activity: "Activity history", noActivity: "No staff updates yet", workflow: "Order progress", mockNote: "Simulation only. These controls do not charge, refund, dispatch parcels or send emails.", carrier: "Carrier / delivery service", tracking: "Tracking reference", nextStage: "Next step", applyStage: "Apply simulated step", finished: "No further transitions available", delivery: "Notification delivery", simulate: "Run mock delivery", retry: "Retry mock delivery", outcome: "Test outcome", success: "Success", failure: "Failure", attempts: "Attempts", exhausted: "Retry limit reached. Review the request before creating a new notification.", allRequests: "All requests", allAssignees: "All assignments", assigned: "Assigned", unassignedFilter: "Unassigned", shippingTerms: "Delivery and returns", viewProgress: "View saved request progress", requestCreated: "Request created", requestUpdated: "Request updated", orderTransition: "Simulated order update", mockStaff: "Mock staff", mockCustomer: "Mock customer", fieldNames: { status: "Status", notes: "Notes", assignedTo: "Assignment" },
  stages: { enquiry: "Enquiry received", "awaiting-payment": "Awaiting simulated payment", paid: "Simulated payment confirmed", processing: "Preparing order", shipped: "Simulated shipment", delivered: "Simulated delivery complete", cancelled: "Cancelled", refunded: "Simulated refund complete" },
  deliveryStates: { preview: "Ready for simulation", "mock-delivered": "Simulated delivery successful", failed: "Simulated delivery failed", exhausted: "Retries exhausted" },
};
export const workflowCopy: Localized<typeof en> = {
  ar: workflowArabic, en, th: {
  wholesaleLink: "สอบถามสำหรับธุรกิจ", requestsTitle: "รายการที่บันทึกในเบราว์เซอร์นี้", requestsNote: "ประวัติตัวอย่างเฉพาะเบราว์เซอร์นี้ การติดตามพัสดุและการชำระเงินเป็นการจำลอง", noRequests: "รายการสั่งซื้อตัวอย่างที่บันทึกจะแสดงที่นี่", cancelRequest: "ยกเลิกรายการจำลองนี้",
  wholesaleTitle: "แจ้งความต้องการสำหรับธุรกิจของคุณ", product: "สินค้า", chooseProduct: "เลือกสินค้า", quantity: "จำนวนที่สนใจ (ชิ้น)", business: "ชื่อธุรกิจ / ประเภทธุรกิจ", destination: "จังหวัด รหัสไปรษณีย์ หรือปลายทางจัดส่ง", neededBy: "วันที่ต้องการรับสินค้า (ไม่บังคับ)", phone: "โทรศัพท์ (ไม่บังคับ)", wholesaleNote: "แบบฟอร์มนี้เป็นการสอบถาม ทีมงานต้องยืนยันสินค้าพร้อมจำหน่าย จำนวนขั้นต่ำ ราคา และวันจัดส่งก่อนดำเนินการ",
  assignedTo: "ผู้รับผิดชอบ", unassigned: "ยังไม่มอบหมาย", saveAssignment: "บันทึกผู้รับผิดชอบ", saved: "บันทึกแล้ว", failed: "บันทึกไม่สำเร็จ กรุณาตรวจสอบข้อมูลและลองอีกครั้ง ข้อมูลที่กรอกยังอยู่", activity: "ประวัติการดำเนินการ", noActivity: "ยังไม่มีการอัปเดตจากทีมงาน", workflow: "ความคืบหน้ารายการสั่งซื้อ", mockNote: "การจำลองเท่านั้น ปุ่มเหล่านี้ไม่เรียกเก็บเงิน คืนเงินจริง ส่งพัสดุ หรือส่งอีเมล", carrier: "ผู้ให้บริการจัดส่ง", tracking: "เลขติดตามพัสดุ", nextStage: "ขั้นตอนถัดไป", applyStage: "บันทึกขั้นตอนจำลอง", finished: "ไม่มีขั้นตอนถัดไป", delivery: "การส่งการแจ้งเตือน", simulate: "ทดลองส่งการแจ้งเตือน", retry: "ลองส่งตัวอย่างอีกครั้ง", outcome: "ผลลัพธ์ที่ต้องการทดสอบ", success: "สำเร็จ", failure: "ไม่สำเร็จ", attempts: "จำนวนครั้ง", exhausted: "ครบจำนวนครั้งที่ลองใหม่แล้ว กรุณาตรวจสอบรายการก่อนสร้างการแจ้งเตือนใหม่", allRequests: "คำขอทุกรูปแบบ", allAssignees: "ผู้รับผิดชอบทั้งหมด", assigned: "มอบหมายแล้ว", unassignedFilter: "ยังไม่มอบหมาย", shippingTerms: "การจัดส่งและการคืนสินค้า", viewProgress: "ดูความคืบหน้ารายการที่บันทึก", requestCreated: "สร้างคำขอ", requestUpdated: "แก้ไขคำขอ", orderTransition: "อัปเดตคำสั่งซื้อจำลอง", mockStaff: "ทีมงานตัวอย่าง", mockCustomer: "ลูกค้าตัวอย่าง", fieldNames: { status: "สถานะ", notes: "บันทึก", assignedTo: "ผู้รับผิดชอบ" },
  stages: { enquiry: "ได้รับคำสอบถาม", "awaiting-payment": "รอชำระเงินจำลอง", paid: "ยืนยันการชำระเงินจำลอง", processing: "เตรียมสินค้า", shipped: "จัดส่งจำลอง", delivered: "รับสินค้าจำลองแล้ว", cancelled: "ยกเลิกแล้ว", refunded: "คืนเงินจำลองแล้ว" },
  deliveryStates: { preview: "พร้อมทดสอบการส่ง", "mock-delivered": "ส่งตัวอย่างสำเร็จ", failed: "ส่งตัวอย่างไม่สำเร็จ", exhausted: "ครบจำนวนครั้งที่ลองใหม่" },
} };
