import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import ts from 'typescript';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
function load(relative) {
  const record = { exports: {} };
  const code = ts.transpileModule(fs.readFileSync(path.join(root, relative), 'utf8'), { compilerOptions: { module: ts.ModuleKind.CommonJS, target: ts.ScriptTarget.ES2022 } }).outputText;
  const require = (name) => {
    if (name === 'react') return { useRef: (current) => ({ current }) };
    if (name === '@/lib/gallery-swipe') return load('src/lib/gallery-swipe.ts');
    throw new Error(`Unexpected gallery test import: ${name}`);
  };
  new Function('require', 'module', 'exports', code)(require, record, record.exports);
  return record.exports;
}
const { initialState, sliderReducer: reduce, nextAvailable } = load('src/lib/gallery-state.ts');
const { swipeAxis, swipeDirection, decodeGalleryImage } = load('src/lib/gallery-swipe.ts');
let state = reduce(initialState, { type: 'loaded', index: 0 });
state = reduce(state, { type: 'request', index: 1, total: 16, announcement: 'Second' });
assert.equal(state.active, 0); assert.equal(state.pending, 1); assert.equal(state.announcement, '');
console.log('PASS: delayed image keeps the visible image and caption until ready');
state = reduce(state, { type: 'request', index: 8, total: 16, announcement: 'Ninth' });
state = reduce(state, { type: 'loaded', index: 1 });
assert.equal(state.active, 0); assert.equal(state.pending, 8);
state = reduce(state, { type: 'loaded', index: 8 });
assert.equal(state.active, 8); assert.equal(state.pending, null); assert.equal(state.outgoing, 0); assert.equal(state.announcement, 'Ninth');
console.log('PASS: rapid requests ignore late completion from an older selection');
const transition = state.transitionId;
state = reduce(state, { type: 'loaded', index: 9 });
state = reduce(state, { type: 'request', index: 9, total: 16 });
state = reduce(state, { type: 'settled', transitionId: transition });
assert.equal(state.outgoing, 8);
state = reduce(state, { type: 'settled', transitionId: state.transitionId });
assert.equal(state.outgoing, null);
console.log('PASS: old animation completion cannot remove the current transition');
state = reduce(state, { type: 'request', index: 12, total: 16 });
state = reduce(state, { type: 'failed', index: 12, total: 16 });
assert.equal(state.active, 9); assert.equal(state.pending, null); assert.ok(state.failed.has(12));
state = reduce(state, { type: 'retry', index: 12, total: 16 });
assert.equal(state.active, 9); assert.equal(state.pending, 12); assert.ok(!state.failed.has(12));
state = reduce(state, { type: 'loaded', index: 12 }); assert.equal(state.active, 12);
console.log('PASS: failed requests retain the current image and explicit retry recovers');
assert.equal(nextAvailable(15, 1, 16, new Set([0, 1])), 2);
assert.equal(nextAvailable(0, -1, 16, new Set([15])), 14);
assert.equal(nextAvailable(0, 1, 1, new Set()), 0);
assert.equal(nextAvailable(0, 1, 3, new Set([1, 2])), 0);
console.log('PASS: navigation wraps a 16-image gallery and skips unavailable images');
assert.equal(swipeAxis('pending', 2, 4), 'pending');
assert.equal(swipeAxis('pending', 12, 40), 'vertical');
assert.equal(swipeAxis('vertical', 100, 40), 'vertical');
assert.equal(swipeAxis('pending', 16, 15), 'vertical');
assert.equal(swipeDirection('vertical', -150, 320), 0);
assert.equal(swipeDirection('pending', -150, 320), 0);
assert.equal(swipeDirection('horizontal', -12, 320), 0);
assert.equal(swipeDirection('horizontal', -45, 320), 1);
assert.equal(swipeDirection('horizontal', 90, 1920), -1);
console.log('PASS: vertical and diagonal scrolling never turn into image swipes');
const image = { currentSrc: 'a.webp', isConnected: true, complete: true, naturalWidth: 100, decode: async () => {} };
assert.equal(await decodeGalleryImage(image), true);
assert.equal(await decodeGalleryImage({ ...image, decode: async () => { throw new Error('cached image'); } }), true);
assert.equal(await decodeGalleryImage({ ...image, naturalWidth: 0 }), false);
assert.equal(await decodeGalleryImage({ ...image, isConnected: false }), false);
const changing = { ...image, decode: async () => { changing.currentSrc = 'new.webp'; } };
assert.equal(await decodeGalleryImage(changing), false);
console.log('PASS: image decoding rejects stale, detached and broken image completions');
let failedInitial = reduce(initialState, { type: 'failed', index: 0, total: 2 });
assert.equal(failedInitial.pending, 1);
failedInitial = reduce(failedInitial, { type: 'loaded', index: 1 });
assert.equal(failedInitial.active, 1); assert.ok(!failedInitial.loaded.has(0));
console.log('PASS: an unavailable initial image advances safely to a decoded alternative');
const { useGallerySwipe: createSwipeHandlers } = load('src/components/useGallerySwipe.ts');
const moves = [], captures = new Set();
let direction = "ltr";
globalThis.getComputedStyle = () => ({ direction });
const swipe = createSwipeHandlers((direction) => moves.push(direction));
const target = { clientWidth: 320, hasPointerCapture: (id) => captures.has(id), setPointerCapture: (id) => captures.add(id) };
const pointer = (x, y) => ({ isPrimary: true, pointerType: 'touch', pointerId: 1, clientX: x, clientY: y, currentTarget: target });
let cancelled = false;
const click = { detail: 1, preventDefault: () => { cancelled = true; }, stopPropagation() {} };
swipe.onPointerDown(pointer(100, 20)); swipe.onPointerUp(pointer(102, 22)); swipe.onClickCapture(click);
assert.equal(captures.size, 0); assert.equal(cancelled, false); assert.deepEqual(moves, []);
swipe.onPointerDown(pointer(150, 20)); swipe.onPointerMove(pointer(70, 25)); swipe.onPointerUp(pointer(30, 25)); swipe.onClickCapture(click);
assert.equal(captures.size, 1); assert.equal(cancelled, true); assert.deepEqual(moves, [1]);
captures.clear(); cancelled = false;
swipe.onPointerDown(pointer(100, 20)); swipe.onPointerMove(pointer(90, 80)); swipe.onPointerMove(pointer(10, 95)); swipe.onPointerUp(pointer(10, 95)); swipe.onClickCapture(click);
assert.equal(captures.size, 0); assert.equal(cancelled, false); assert.deepEqual(moves, [1]);
console.log('PASS: ordinary taps keep nested links clickable; only horizontal swipes suppress clicks');

direction = "rtl";
swipe.onPointerDown(pointer(30, 20)); swipe.onPointerMove(pointer(100, 20)); swipe.onPointerUp(pointer(160, 20));
assert.deepEqual(moves, [1, 1]);
console.log("PASS: Arabic swipe direction follows RTL gallery order");
delete globalThis.getComputedStyle;
